// Auto-generated by tools/_build_battle_fx_cues_js.js — 手で編集しない。
// 元データ: reference/battle_fx_cues.json (演出ツクール=fx_editor.htmlの書き出しSSOT)
// 設計: 設計_演出ツクール_2026-07-11.md(1-1キューシート/1-2 cuePlayer=上書きオーバーレイ方式)
// real_battle.html / online_battle.html の resolveCueSheet/playCueSheet(fx_primitives.js)が読む。
// キー = move:技名(個別上書き) / pattern:タイプ+分類(一括既定) / __board(エディタの立ち位置・本番では無視)。
// done===true のシートだけ本番で再生される(ドラフト中は従来の自動演出のまま=挙動不変)。
// 生成: 2026-07-16T04:04:04.621Z
window.BATTLE_FX_CUES = {
  "move:フレアドライブ": {
    "dur": 2270,
    "done": true,
    "cues": [
      {
        "id": "c1",
        "track": "atk",
        "action": "charge",
        "t": 0,
        "dur": 800,
        "params": {
          "shape": "flame",
          "cls": "phys"
        }
      },
      {
        "id": "c2",
        "track": "glyph",
        "action": "burst",
        "t": 550,
        "dur": 1600,
        "params": {
          "shape": "flame",
          "intensity": "normal",
          "at": "opp",
          "offset": {
            "x": -9,
            "y": 24
          },
          "scale": 2
        }
      },
      {
        "id": "c3",
        "track": "sound",
        "action": "se",
        "t": 350,
        "dur": 100,
        "params": {
          "cls": "phys"
        }
      },
      {
        "id": "c4",
        "track": "screen",
        "action": "shake",
        "t": 350,
        "dur": 280,
        "params": {
          "mag": 1
        }
      },
      {
        "id": "c5",
        "track": "def",
        "action": "knockback",
        "t": 350,
        "dur": 280,
        "params": {
          "at": "opp"
        }
      },
      {
        "id": "c6",
        "track": "text",
        "action": "popnum",
        "t": 600,
        "dur": 1550,
        "params": {
          "at": "opp",
          "text": "−42",
          "scale": 1,
          "size": 25,
          "rise": 20,
          "fadeMs": 2000
        }
      }
    ]
  },
  "class:phys_contact": {
    "dur": 2270,
    "done": true,
    "_note": "物理・接触(殴ってぶつかる系)の全技共通デフォルト(2026-07-16 阿部さん)。フレアドライブ基準のタイミング/位置。shapeはあえて持たず shapeOf(mv) が技ごとの絵(fist/water/fang...)を出す。resolveCueSheetの3段目(move:→pattern:→class:)。move:個別上書きが優先。",
    "cues": [
      {
        "id": "c1",
        "track": "atk",
        "action": "charge",
        "t": 0,
        "dur": 800,
        "params": {
          "cls": "phys"
        }
      },
      {
        "id": "c2",
        "track": "glyph",
        "action": "burst",
        "t": 550,
        "dur": 1600,
        "params": {
          "intensity": "normal",
          "at": "opp",
          "offset": {
            "x": -9,
            "y": 24
          },
          "scale": 2
        }
      },
      {
        "id": "c3",
        "track": "sound",
        "action": "se",
        "t": 350,
        "dur": 100,
        "params": {
          "cls": "phys"
        }
      },
      {
        "id": "c4",
        "track": "screen",
        "action": "shake",
        "t": 350,
        "dur": 280,
        "params": {
          "mag": 1
        }
      },
      {
        "id": "c5",
        "track": "def",
        "action": "knockback",
        "t": 350,
        "dur": 280,
        "params": {
          "at": "opp"
        }
      },
      {
        "id": "c6",
        "track": "text",
        "action": "popnum",
        "t": 600,
        "dur": 1550,
        "params": {
          "at": "opp",
          "text": "−42",
          "scale": 1,
          "size": 25,
          "rise": 20,
          "fadeMs": 2000
        }
      }
    ]
  }
};
