// Auto-generated by tools/_build_battle_fx_cues_js.js — 手で編集しない。
// 元データ: reference/battle_fx_cues.json (演出ツクール=fx_editor.htmlの書き出しSSOT)
// 設計: 設計_演出ツクール_2026-07-11.md(1-1キューシート/1-2 cuePlayer=上書きオーバーレイ方式)
// real_battle.html / online_battle.html の resolveCueSheet/playCueSheet(fx_primitives.js)が読む。
// キー = move:技名(個別上書き) / pattern:タイプ+分類(一括既定) / __board(エディタの立ち位置・本番では無視)。
// done===true のシートだけ本番で再生される(ドラフト中は従来の自動演出のまま=挙動不変)。
// 生成: 2026-07-15T12:55:03.900Z
window.BATTLE_FX_CUES = {
  "move:はたく": {
    "dur": 1380,
    "done": true,
    "cues": [
      {
        "id": "c1",
        "track": "atk",
        "action": "charge",
        "t": 0,
        "dur": 480,
        "params": {
          "shape": "fist",
          "cls": "phys"
        }
      },
      {
        "id": "c2",
        "track": "glyph",
        "action": "burst",
        "t": 260,
        "dur": 650,
        "params": {
          "shape": "fist",
          "intensity": "normal",
          "at": "opp"
        }
      },
      {
        "id": "c3",
        "track": "sound",
        "action": "se",
        "t": 260,
        "dur": 120,
        "params": {
          "cls": "phys"
        }
      },
      {
        "id": "c4",
        "track": "screen",
        "action": "shake",
        "t": 260,
        "dur": 280,
        "params": {
          "mag": 1
        }
      },
      {
        "id": "c5",
        "track": "def",
        "action": "knockback",
        "t": 260,
        "dur": 280,
        "params": {
          "at": "opp"
        }
      },
      {
        "id": "c6",
        "track": "text",
        "action": "popnum",
        "t": 260,
        "dur": 1000,
        "params": {
          "at": "opp",
          "text": "−42"
        }
      }
    ]
  },
  "move:フレアドライブ": {
    "dur": 2580,
    "done": true,
    "cues": [
      {
        "id": "c1",
        "track": "atk",
        "action": "charge",
        "t": 0,
        "dur": 550,
        "params": {
          "shape": "flame",
          "cls": "phys"
        }
      },
      {
        "id": "c2",
        "track": "glyph",
        "action": "burst",
        "t": 260,
        "dur": 1950,
        "params": {
          "shape": "flame",
          "intensity": "normal",
          "at": "opp",
          "offset": {
            "x": -4,
            "y": 21
          },
          "scale": 2
        }
      },
      {
        "id": "c3",
        "track": "sound",
        "action": "se",
        "t": 260,
        "dur": 120,
        "params": {
          "cls": "phys"
        }
      },
      {
        "id": "c4",
        "track": "screen",
        "action": "shake",
        "t": 260,
        "dur": 280,
        "params": {
          "mag": 1
        }
      },
      {
        "id": "c5",
        "track": "def",
        "action": "knockback",
        "t": 260,
        "dur": 280,
        "params": {
          "at": "opp"
        }
      },
      {
        "id": "c6",
        "track": "text",
        "action": "popnum",
        "t": 460,
        "dur": 2000,
        "params": {
          "at": "opp",
          "text": "−42"
        }
      }
    ]
  }
};
