// Auto-generated from _review/items_database.json (2026-06-19 レギュMB追加で計159件)
// メガストーン: 76件 / 通常持ち物: 83件
// ポケチャン実装済の持ち物。party_checker.html と battle_simulator.html・real_battle_simulator.html で共有。
window.ITEMS_DATABASE = {
  "version": "1.0",
  "updated": "2026-06-19",
  "context": "ポケモンチャンピオンズ (ポケチャン) battle_simulator.html 用持ち物マスタ",
  "sources": {
    "primary": "vgc-champions-calc.pages.dev バンドル解析 (2026-05-16, /assets/index-Bt-7Kz3C.js)",
    "secondary": [
      "アルテマ ポケチャン持ち物一覧 https://altema.jp/pokemonchampions/itemlist",
      "アルテマ ポケチャン未実装持ち物 https://altema.jp/pokemonchampions/mijisouitemlist",
      "Gamerch ポケチャン道具 https://gamerch.com/pokemonchampions/980380",
      "AppMedia ポケチャン持ち物 https://appmedia.jp/pokemonchampions/79922272",
      "Game8 ポケチャン道具 https://game8.jp/pokemon-champions/775655",
      "GameWith ポケチャン持ち物 https://gamewith.jp/pokemon-champions/546487"
    ]
  },
  "categories": {
    "attack_boost": "攻撃側威力補正",
    "type_boost": "タイプ別威力補正 (×1.2 / Q12=4915)",
    "berry_resist": "半減きのみ (×0.5 / Q12=2048, 効果バツグン時のみ発動・1回)",
    "berry_status_cure": "状態異常回復きのみ",
    "berry_hp_cure": "HP回復きのみ",
    "defense_boost": "防御補正",
    "status_inflict": "状態異常付与 (装備者デメリット系)",
    "hp_drain": "HP回復/反動",
    "speed_boost": "素早さ補正",
    "survival": "生存補助 (タスキ/ハチマキ等)",
    "misc": "その他",
    "mega_stone": "メガストーン (メガシンカ起動)"
  },
  "schema_notes": {
    "q12": "4096分のN表現の整数倍率。例: 6144 → ×1.5。null は未確定または倍率を持たない。",
    "factor": "倍率の小数表現。q12/4096 と一致。",
    "implemented_in_pokechan": "ポケチャンに実装されているかのフラグ。false なら本家にあるがポケチャン未解禁。",
    "source_q12": "Q12値の出典。 'vgc-champions-calc' = バンドル解析で確認、'spec_pokemon_main' = 本家ポケモン仕様準拠 (要検証)。",
    "verify": "true なら未確認・要追加検証。false なら確定済み。",
    "mega_target_en": "メガストーンの対象ポケモン英語名 (key の suffix と対応)",
    "mega_form": "メガシンカ後の名称 (例: メガリザードンX)",
    "mega_types": "メガシンカ後のタイプ配列 (null は未収集)",
    "mega_ability": "メガシンカ後の特性 (null は未収集)",
    "mega_ability_desc": "メガシンカ後特性の効果説明 (null は未収集)",
    "mega_stats": "メガシンカ後の種族値 {H,A,B,C,D,S} (null は未収集)",
    "acquisition": "入手区分: tutorial_free / frontier_shop_2000VP / za_link / season_m1_reward / season_m1_or_giveaway",
    "acquisition_note": "入手区分の人間可読説明"
  },
  "items": [
    {
      "key": "kodawari_hachimaki",
      "name": "こだわりハチマキ",
      "name_en": "Choice Band",
      "category": "attack_boost",
      "effect": "物理技の攻撃が×1.5になる。同じ技しか出せなくなる。",
      "q12": 6144,
      "factor": 1.5,
      "applies_to": "physical_attack",
      "restriction": "選択技固定",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装 (アルテマ未実装一覧に掲載)"
    },
    {
      "key": "kodawari_megane",
      "name": "こだわりメガネ",
      "name_en": "Choice Specs",
      "category": "attack_boost",
      "effect": "特殊技の特攻が×1.5になる。同じ技しか出せなくなる。",
      "q12": 6144,
      "factor": 1.5,
      "applies_to": "special_attack",
      "restriction": "選択技固定",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装"
    },
    {
      "key": "kodawari_scarf",
      "name": "こだわりスカーフ",
      "name_en": "Choice Scarf",
      "category": "speed_boost",
      "effect": "素早さが×1.5。同じ技しか出せなくなる。",
      "q12": 6144,
      "factor": 1.5,
      "applies_to": "speed",
      "restriction": "選択技固定",
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "verify": false,
      "notes": "初期所持アイテム (ポケチャン)"
    },
    {
      "key": "life_orb",
      "name": "いのちのたま",
      "name_en": "Life Orb",
      "category": "attack_boost",
      "effect": "技の威力が×1.3。攻撃時に最大HPの1/10の反動。",
      "q12": 5324,
      "factor": 1.2998,
      "applies_to": "damage",
      "drawback": "max_hp / 10 reaction damage",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装"
    },
    {
      "key": "expert_belt",
      "name": "たつじんのおび",
      "name_en": "Expert Belt",
      "category": "attack_boost",
      "effect": "効果バツグンの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "applies_to": "super_effective_damage",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装"
    },
    {
      "key": "muscle_band",
      "name": "ちからのハチマキ",
      "name_en": "Muscle Band",
      "category": "attack_boost",
      "effect": "物理技の威力が×1.1。",
      "q12": 4506,
      "factor": 1.1,
      "applies_to": "physical_damage",
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装"
    },
    {
      "key": "wise_glasses",
      "name": "ものしりメガネ",
      "name_en": "Wise Glasses",
      "category": "attack_boost",
      "effect": "特殊技の威力が×1.1。",
      "q12": 4506,
      "factor": 1.1,
      "applies_to": "special_damage",
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装"
    },
    {
      "key": "punching_glove",
      "name": "パンチグローブ",
      "name_en": "Punching Glove",
      "category": "attack_boost",
      "effect": "パンチ系の技の威力UP、接触判定が消える。",
      "q12": 4506,
      "factor": 1.1,
      "applies_to": "punch_moves",
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": false,
      "verify": true,
      "notes": "ポケチャン未実装。倍率は本家準拠 ×1.1 (要検証)"
    },
    {
      "key": "type_boost_normal",
      "name": "シルクのスカーフ",
      "name_en": "Silk Scarf",
      "category": "type_boost",
      "boost_type": "ノーマル",
      "effect": "ノーマルタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_fire",
      "name": "もくたん",
      "name_en": "Charcoal",
      "category": "type_boost",
      "boost_type": "ほのお",
      "effect": "ほのおタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_water",
      "name": "しんぴのしずく",
      "name_en": "Mystic Water",
      "category": "type_boost",
      "boost_type": "みず",
      "effect": "みずタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_electric",
      "name": "じしゃく",
      "name_en": "Magnet",
      "category": "type_boost",
      "boost_type": "でんき",
      "effect": "でんきタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_grass",
      "name": "きせきのタネ",
      "name_en": "Miracle Seed",
      "category": "type_boost",
      "boost_type": "くさ",
      "effect": "くさタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_ice",
      "name": "とけないこおり",
      "name_en": "Never-Melt Ice",
      "category": "type_boost",
      "boost_type": "こおり",
      "effect": "こおりタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_fighting",
      "name": "くろおび",
      "name_en": "Black Belt",
      "category": "type_boost",
      "boost_type": "かくとう",
      "effect": "かくとうタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_poison",
      "name": "どくバリ",
      "name_en": "Poison Barb",
      "category": "type_boost",
      "boost_type": "どく",
      "effect": "どくタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_ground",
      "name": "やわらかいすな",
      "name_en": "Soft Sand",
      "category": "type_boost",
      "boost_type": "じめん",
      "effect": "じめんタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_flying",
      "name": "するどいくちばし",
      "name_en": "Sharp Beak",
      "category": "type_boost",
      "boost_type": "ひこう",
      "effect": "ひこうタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_psychic",
      "name": "まがったスプーン",
      "name_en": "Twisted Spoon",
      "category": "type_boost",
      "boost_type": "エスパー",
      "effect": "エスパータイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_bug",
      "name": "ぎんのこな",
      "name_en": "Silver Powder",
      "category": "type_boost",
      "boost_type": "むし",
      "effect": "むしタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_rock",
      "name": "かたいいし",
      "name_en": "Hard Stone",
      "category": "type_boost",
      "boost_type": "いわ",
      "effect": "いわタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_ghost",
      "name": "のろいのおふだ",
      "name_en": "Spell Tag",
      "category": "type_boost",
      "boost_type": "ゴースト",
      "effect": "ゴーストタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_dragon",
      "name": "りゅうのキバ",
      "name_en": "Dragon Fang",
      "category": "type_boost",
      "boost_type": "ドラゴン",
      "effect": "ドラゴンタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_dark",
      "name": "くろいメガネ",
      "name_en": "Black Glasses",
      "category": "type_boost",
      "boost_type": "あく",
      "effect": "あくタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_steel",
      "name": "メタルコート",
      "name_en": "Metal Coat",
      "category": "type_boost",
      "boost_type": "はがね",
      "effect": "はがねタイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "type_boost_fairy",
      "name": "ようせいのハネ",
      "name_en": "Fairy Feather",
      "category": "type_boost",
      "boost_type": "フェアリー",
      "effect": "フェアリータイプの技の威力が×1.2。",
      "q12": 4915,
      "factor": 1.2,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "berry_resist_normal",
      "name": "ホズのみ",
      "name_en": "Chilan Berry",
      "category": "berry_resist",
      "resist_type": "ノーマル",
      "effect": "ノーマルタイプの技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "first_normal_hit",
      "source_q12": "vgc-champions-calc (半減きのみ汎用)",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false,
      "notes": "本家ではノーマル全般 (タイプ一致時) 半減仕様。ポケチャン挙動は要確認。"
    },
    {
      "key": "berry_resist_fire",
      "name": "オッカのみ",
      "name_en": "Occa Berry",
      "category": "berry_resist",
      "resist_type": "ほのお",
      "effect": "効果バツグンのほのお技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_water",
      "name": "イトケのみ",
      "name_en": "Passho Berry",
      "category": "berry_resist",
      "resist_type": "みず",
      "effect": "効果バツグンのみず技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_electric",
      "name": "ソクノのみ",
      "name_en": "Wacan Berry",
      "category": "berry_resist",
      "resist_type": "でんき",
      "effect": "効果バツグンのでんき技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_grass",
      "name": "リンドのみ",
      "name_en": "Rindo Berry",
      "category": "berry_resist",
      "resist_type": "くさ",
      "effect": "効果バツグンのくさ技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_ice",
      "name": "ヤチェのみ",
      "name_en": "Yache Berry",
      "category": "berry_resist",
      "resist_type": "こおり",
      "effect": "効果バツグンのこおり技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_fighting",
      "name": "ヨプのみ",
      "name_en": "Chople Berry",
      "category": "berry_resist",
      "resist_type": "かくとう",
      "effect": "効果バツグンのかくとう技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_poison",
      "name": "ビアーのみ",
      "name_en": "Kebia Berry",
      "category": "berry_resist",
      "resist_type": "どく",
      "effect": "効果バツグンのどく技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_ground",
      "name": "シュカのみ",
      "name_en": "Shuca Berry",
      "category": "berry_resist",
      "resist_type": "じめん",
      "effect": "効果バツグンのじめん技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_flying",
      "name": "バコウのみ",
      "name_en": "Coba Berry",
      "category": "berry_resist",
      "resist_type": "ひこう",
      "effect": "効果バツグンのひこう技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_psychic",
      "name": "ウタンのみ",
      "name_en": "Payapa Berry",
      "category": "berry_resist",
      "resist_type": "エスパー",
      "effect": "効果バツグンのエスパー技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_bug",
      "name": "タンガのみ",
      "name_en": "Tanga Berry",
      "category": "berry_resist",
      "resist_type": "むし",
      "effect": "効果バツグンのむし技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_rock",
      "name": "ヨロギのみ",
      "name_en": "Charti Berry",
      "category": "berry_resist",
      "resist_type": "いわ",
      "effect": "効果バツグンのいわ技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_ghost",
      "name": "カシブのみ",
      "name_en": "Kasib Berry",
      "category": "berry_resist",
      "resist_type": "ゴースト",
      "effect": "効果バツグンのゴースト技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_dragon",
      "name": "ハバンのみ",
      "name_en": "Haban Berry",
      "category": "berry_resist",
      "resist_type": "ドラゴン",
      "effect": "効果バツグンのドラゴン技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_dark",
      "name": "ナモのみ",
      "name_en": "Colbur Berry",
      "category": "berry_resist",
      "resist_type": "あく",
      "effect": "効果バツグンのあく技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_steel",
      "name": "リリバのみ",
      "name_en": "Babiri Berry",
      "category": "berry_resist",
      "resist_type": "はがね",
      "effect": "効果バツグンのはがね技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_resist_fairy",
      "name": "ロゼルのみ",
      "name_en": "Roseli Berry",
      "category": "berry_resist",
      "resist_type": "フェアリー",
      "effect": "効果バツグンのフェアリー技を一度だけ半減。",
      "q12": 2048,
      "factor": 0.5,
      "trigger": "super_effective_only",
      "source_q12": "vgc-champions-calc",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_cure_paralysis",
      "name": "クラボのみ",
      "name_en": "Cheri Berry",
      "category": "berry_status_cure",
      "cure_target": "paralysis",
      "effect": "まひ状態を回復する。",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_cure_sleep",
      "name": "カゴのみ",
      "name_en": "Chesto Berry",
      "category": "berry_status_cure",
      "cure_target": "sleep",
      "effect": "ねむり状態を回復する。",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_cure_poison",
      "name": "モモンのみ",
      "name_en": "Pecha Berry",
      "category": "berry_status_cure",
      "cure_target": "poison",
      "effect": "どく・もうどく状態を回復する。",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_cure_burn",
      "name": "チーゴのみ",
      "name_en": "Rawst Berry",
      "category": "berry_status_cure",
      "cure_target": "burn",
      "effect": "やけど状態を回復する。",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_cure_freeze",
      "name": "ナナシのみ",
      "name_en": "Aspear Berry",
      "category": "berry_status_cure",
      "cure_target": "freeze",
      "effect": "こおり状態を回復する。",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_cure_confusion",
      "name": "キーのみ",
      "name_en": "Persim Berry",
      "category": "berry_status_cure",
      "cure_target": "confusion",
      "effect": "こんらん状態を回復する。",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_cure_all",
      "name": "ラムのみ",
      "name_en": "Lum Berry",
      "category": "berry_status_cure",
      "cure_target": "all",
      "effect": "すべての状態異常・こんらんを1度だけ回復する。",
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "berry_oran",
      "name": "オレンのみ",
      "name_en": "Oran Berry",
      "category": "berry_hp_cure",
      "effect": "HP1/2以下になった時に最大HPの10を回復する。",
      "trigger": "hp_le_50pct",
      "heal_amount_fixed": 10,
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "berry_sitrus",
      "name": "オボンのみ",
      "name_en": "Sitrus Berry",
      "category": "berry_hp_cure",
      "effect": "HP1/2以下になった時に最大HPの1/4を回復する。",
      "trigger": "hp_le_50pct",
      "heal_fraction": "1/4",
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "berry_leppa",
      "name": "ヒメリのみ",
      "name_en": "Leppa Berry",
      "category": "berry_hp_cure",
      "effect": "PPが0になった技のPPを10回復する。",
      "trigger": "pp_zero",
      "implemented_in_pokechan": true,
      "vp_cost": 400,
      "verify": false
    },
    {
      "key": "leftovers",
      "name": "たべのこし",
      "name_en": "Leftovers",
      "category": "hp_drain",
      "effect": "ターン終了時に最大HPの1/16を回復する。",
      "heal_fraction": "1/16",
      "trigger": "end_of_turn",
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "shell_bell",
      "name": "かいがらのすず",
      "name_en": "Shell Bell",
      "category": "hp_drain",
      "effect": "技でダメージを与えた時、与えダメージの1/8を自分のHPとして回復する。",
      "heal_fraction_of_damage": "1/8",
      "trigger": "on_dealing_damage",
      "implemented_in_pokechan": true,
      "vp_cost": 700,
      "verify": false
    },
    {
      "key": "black_sludge",
      "name": "くろいヘドロ",
      "name_en": "Black Sludge",
      "category": "hp_drain",
      "effect": "毒タイプは毎ターン最大HPの1/16回復、それ以外は1/8減少。",
      "heal_fraction_for_poison": "1/16",
      "damage_fraction_for_others": "1/8",
      "trigger": "end_of_turn",
      "implemented_in_pokechan": false,
      "verify": true,
      "notes": "ポケチャンに実装されているか未確認。本家ポケモン仕様を記載。"
    },
    {
      "key": "focus_sash",
      "name": "きあいのタスキ",
      "name_en": "Focus Sash",
      "category": "survival",
      "effect": "HP満タン時に一撃ひんし技のダメージを受けるとHPを1残して耐える (1回)。",
      "trigger": "ohko_at_full_hp",
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "focus_band",
      "name": "きあいのハチマキ",
      "name_en": "Focus Band",
      "category": "survival",
      "effect": "ひんしになる技のダメージを受けると10%の確率でHP1残して耐える。",
      "trigger": "lethal_damage",
      "proc_chance": 0.1,
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "white_herb",
      "name": "しろいハーブ",
      "name_en": "White Herb",
      "category": "survival",
      "effect": "能力ランクが下がったとき1度だけ元に戻す。",
      "trigger": "stat_drop",
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "mental_herb",
      "name": "メンタルハーブ",
      "name_en": "Mental Herb",
      "category": "survival",
      "effect": "アンコール・いちゃもん・かなしばり・どうしても・メロメロを1度だけ回復する。",
      "trigger": "mental_status",
      "implemented_in_pokechan": true,
      "vp_cost": 1000,
      "verify": true,
      "notes": "アルテマ表記準拠。サイト間で説明揺れあり、要ゲーム内確認。"
    },
    {
      "key": "kings_rock",
      "name": "おうじゃのしるし",
      "name_en": "King's Rock",
      "category": "misc",
      "effect": "ダメージを与えた時10%の確率で相手をひるませる。",
      "proc_chance": 0.1,
      "trigger": "on_dealing_damage",
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "quick_claw",
      "name": "せんせいのつめ",
      "name_en": "Quick Claw",
      "category": "speed_boost",
      "effect": "20%の確率で同じ優先度の技の中で最初に行動できる。",
      "proc_chance": 0.2,
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "bright_powder",
      "name": "ひかりのこな",
      "name_en": "Bright Powder",
      "category": "defense_boost",
      "effect": "自分に対する相手の技の命中率を×0.9にする。",
      "factor": 0.9,
      "applies_to": "evasion",
      "implemented_in_pokechan": true,
      "is_default": true,
      "verify": false
    },
    {
      "key": "scope_lens",
      "name": "ピントレンズ",
      "name_en": "Scope Lens",
      "category": "attack_boost",
      "effect": "急所ランク+1。",
      "applies_to": "critical_rate",
      "implemented_in_pokechan": true,
      "vp_cost": 1000,
      "verify": false
    },
    {
      "key": "light_ball",
      "name": "でんきだま",
      "name_en": "Light Ball",
      "category": "attack_boost",
      "effect": "ピカチュウの攻撃と特攻が2倍。",
      "factor": 2,
      "restriction": "pikachu_only",
      "implemented_in_pokechan": true,
      "vp_cost": 1000,
      "verify": false
    },
    {
      "key": "assault_vest",
      "name": "とつげきチョッキ",
      "name_en": "Assault Vest",
      "category": "defense_boost",
      "effect": "特防が×1.5になる。変化技は使えない。",
      "q12": 6144,
      "factor": 1.5,
      "applies_to": "special_defense",
      "restriction": "no_status_moves",
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装"
    },
    {
      "key": "eviolite",
      "name": "しんかのきせき",
      "name_en": "Eviolite",
      "category": "defense_boost",
      "effect": "進化前ポケモンの防御・特防が×1.5になる。",
      "q12": 6144,
      "factor": 1.5,
      "applies_to": "defense_and_sp_defense",
      "restriction": "not_fully_evolved",
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装 (アルテマ未実装一覧で確認)"
    },
    {
      "key": "air_balloon",
      "name": "ふうせん",
      "name_en": "Air Balloon",
      "category": "defense_boost",
      "effect": "じめんタイプの技を1度だけ無効化する。攻撃を受けると割れて効果消失。",
      "trigger": "ground_attack_received",
      "implemented_in_pokechan": false,
      "verify": true,
      "notes": "ポケチャン実装状況未確認 (要追加調査)"
    },
    {
      "key": "rocky_helmet",
      "name": "ゴツゴツメット",
      "name_en": "Rocky Helmet",
      "category": "defense_boost",
      "effect": "接触技で攻撃された時、攻撃側に最大HPの1/6のダメージ。",
      "damage_fraction_to_attacker": "1/6",
      "trigger": "contact_received",
      "implemented_in_pokechan": false,
      "verify": true,
      "notes": "battle_simulator.html に既に data-flag=rockyHelmet として実装あり (本家準拠の挙動)"
    },
    {
      "key": "flame_orb",
      "name": "かえんだま",
      "name_en": "Flame Orb",
      "category": "status_inflict",
      "effect": "持っているとターン終了時にやけど状態になる。",
      "trigger": "end_of_turn",
      "self_inflict": "burn",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装"
    },
    {
      "key": "toxic_orb",
      "name": "どくどくだま",
      "name_en": "Toxic Orb",
      "category": "status_inflict",
      "effect": "持っているとターン終了時にもうどく状態になる。",
      "trigger": "end_of_turn",
      "self_inflict": "badly_poisoned",
      "implemented_in_pokechan": false,
      "verify": false,
      "notes": "ポケチャン未実装"
    },
    {
      "key": "mega_stone_marker",
      "name": "メガストーン (汎用)",
      "category": "mega_stone",
      "effect": "対象ポケモンがメガシンカできる (戦闘中1回)。詳細は items_data_pokechan.md の 7-3 セクション参照。",
      "implemented_in_pokechan": true,
      "verify": false,
      "notes": "ポケチャンには全60種類のメガストーンが実装されている (HANDOFF の『メガ石無し』前提は誤り)。個別データは別ファイル参照。"
    },
    {
      "key": "mega_stone_clefable",
      "name": "ピクシナイト",
      "name_en": "Clefableite",
      "category": "mega_stone",
      "effect": "ピクシー を メガピクシー にメガシンカさせる (戦闘中1回)",
      "applies_to": "ピクシー",
      "restriction": "ピクシー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガピクシー",
      "mega_target_en": "Clefable",
      "mega_types": [
        "フェアリー"
      ],
      "mega_ability": "マジックミラー",
      "mega_ability_desc": "マジックコートで跳ね返せる変化技を相手に跳ね返す",
      "mega_stats": {
        "H": 95,
        "A": 80,
        "B": 93,
        "C": 135,
        "D": 110,
        "S": 70
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_victreebel",
      "name": "ウツボットナイト",
      "name_en": "Victreebelite",
      "category": "mega_stone",
      "effect": "ウツボット を メガウツボット にメガシンカさせる (戦闘中1回)",
      "applies_to": "ウツボット",
      "restriction": "ウツボット のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガウツボット",
      "mega_target_en": "Victreebel",
      "mega_types": [
        "くさ",
        "どく"
      ],
      "mega_ability": "とびだすなかみ",
      "mega_ability_desc": "技でひんしになった際、最後の技で残っていたHP分を相手に与える",
      "mega_stats": {
        "H": 80,
        "A": 125,
        "B": 85,
        "C": 135,
        "D": 95,
        "S": 70
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_starmie",
      "name": "スターミナイト",
      "name_en": "Starmieite",
      "category": "mega_stone",
      "effect": "スターミー を メガスターミー にメガシンカさせる (戦闘中1回)",
      "applies_to": "スターミー",
      "restriction": "スターミー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガスターミー",
      "mega_target_en": "Starmie",
      "mega_types": [
        "みず",
        "エスパー"
      ],
      "mega_ability": "ちからもち",
      "mega_ability_desc": "自分のこうげき実数値が2倍になる",
      "mega_stats": {
        "H": 60,
        "A": 100,
        "B": 105,
        "C": 130,
        "D": 105,
        "S": 120
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_dragonite",
      "name": "カイリュナイト",
      "name_en": "Dragoniteite",
      "category": "mega_stone",
      "effect": "カイリュー を メガカイリュー にメガシンカさせる (戦闘中1回)",
      "applies_to": "カイリュー",
      "restriction": "カイリュー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "season_m1_or_giveaway",
      "acquisition_note": "シーズン M-1 報酬 / ふしぎな贈り物配布",
      "mega_form": "メガカイリュー",
      "mega_target_en": "Dragonite",
      "mega_types": [
        "ドラゴン",
        "ひこう"
      ],
      "mega_ability": "マルチスケイル",
      "mega_ability_desc": "最大HP時に技ダメージを半減する",
      "mega_stats": {
        "H": 91,
        "A": 124,
        "B": 115,
        "C": 145,
        "D": 125,
        "S": 100
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_meganium",
      "name": "メガニウムナイト",
      "name_en": "Meganiumite",
      "category": "mega_stone",
      "effect": "メガニウム を メガメガニウム にメガシンカさせる (戦闘中1回)",
      "applies_to": "メガニウム",
      "restriction": "メガニウム のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "season_m1_reward",
      "acquisition_note": "シーズン M-1 報酬",
      "mega_form": "メガメガニウム",
      "mega_target_en": "Meganium",
      "mega_types": [
        "くさ"
      ],
      "mega_ability": "メガソーラー",
      "mega_ability_desc": "自分の技使用時、天気が「にほんばれ」と同じ扱いになる",
      "mega_stats": {
        "H": 80,
        "A": 92,
        "B": 115,
        "C": 143,
        "D": 115,
        "S": 80
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia は タイプ=くさ/フェアリー と表記。攻略大百科の くさ単 を採用"
    },
    {
      "key": "mega_stone_feraligatr",
      "name": "オーダイルナイト",
      "name_en": "Feraligatrite",
      "category": "mega_stone",
      "effect": "オーダイル を メガオーダイル にメガシンカさせる (戦闘中1回)",
      "applies_to": "オーダイル",
      "restriction": "オーダイル のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "season_m1_reward",
      "acquisition_note": "シーズン M-1 報酬",
      "mega_form": "メガオーダイル",
      "mega_target_en": "Feraligatr",
      "mega_types": [
        "みず",
        "ドラゴン"
      ],
      "mega_ability": "ドラゴンスキン",
      "mega_ability_desc": "ノーマル技がドラゴン化、威力1.2倍",
      "mega_stats": {
        "H": 85,
        "A": 160,
        "B": 125,
        "C": 89,
        "D": 93,
        "S": 78
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_skarmory",
      "name": "エアームドナイト",
      "name_en": "Skarmoryite",
      "category": "mega_stone",
      "effect": "エアームド を メガエアームド にメガシンカさせる (戦闘中1回)",
      "applies_to": "エアームド",
      "restriction": "エアームド のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガエアームド",
      "mega_target_en": "Skarmory",
      "mega_types": [
        "はがね",
        "ひこう"
      ],
      "mega_ability": "すじがねいり",
      "mega_ability_desc": "攻撃対象変更効果を受けず攻撃できる",
      "mega_stats": {
        "H": 65,
        "A": 140,
        "B": 110,
        "C": 40,
        "D": 100,
        "S": 110
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_chimecho",
      "name": "チリーンナイト",
      "name_en": "Chimechoite",
      "category": "mega_stone",
      "effect": "チリーン を メガチリーン にメガシンカさせる (戦闘中1回)",
      "applies_to": "チリーン",
      "restriction": "チリーン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガチリーン",
      "mega_target_en": "Chimecho",
      "mega_types": [
        "エスパー"
      ],
      "mega_ability": "ふゆう",
      "mega_ability_desc": "じめん技・フィールド効果を受けない",
      "mega_stats": {
        "H": 75,
        "A": 50,
        "B": 110,
        "C": 135,
        "D": 120,
        "S": 65
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia は タイプ=エスパー/はがね と表記。攻略大百科の エスパー単 を採用"
    },
    {
      "key": "mega_stone_froslass",
      "name": "ユキメノコナイト",
      "name_en": "Froslassite",
      "category": "mega_stone",
      "effect": "ユキメノコ を メガユキメノコ にメガシンカさせる (戦闘中1回)",
      "applies_to": "ユキメノコ",
      "restriction": "ユキメノコ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガユキメノコ",
      "mega_target_en": "Froslass",
      "mega_types": [
        "こおり",
        "ゴースト"
      ],
      "mega_ability": "ゆきふらし",
      "mega_ability_desc": "場に出ると5ターン天候がゆきになる",
      "mega_stats": {
        "H": 70,
        "A": 80,
        "B": 70,
        "C": 140,
        "D": 100,
        "S": 120
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_emboar",
      "name": "エンブオナイト",
      "name_en": "Emboarite",
      "category": "mega_stone",
      "effect": "エンブオー を メガエンブオー にメガシンカさせる (戦闘中1回)",
      "applies_to": "エンブオー",
      "restriction": "エンブオー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "season_m1_reward",
      "acquisition_note": "シーズン M-1 報酬",
      "mega_form": "メガエンブオー",
      "mega_target_en": "Emboar",
      "mega_types": [
        "ほのお",
        "みず"
      ],
      "mega_ability": "かたやぶり",
      "mega_ability_desc": "相手特性を無視して攻撃",
      "mega_stats": {
        "H": 110,
        "A": 148,
        "B": 75,
        "C": 110,
        "D": 110,
        "S": 75
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia は タイプ=ほのお/かくとう (従来仕様) と表記。攻略大百科の ほのお/みず を採用"
    },
    {
      "key": "mega_stone_excadrill",
      "name": "ドリュウズナイト",
      "name_en": "Excadrillite",
      "category": "mega_stone",
      "effect": "ドリュウズ を メガドリュウズ にメガシンカさせる (戦闘中1回)",
      "applies_to": "ドリュウズ",
      "restriction": "ドリュウズ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガドリュウズ",
      "mega_target_en": "Excadrill",
      "mega_types": [
        "じめん",
        "はがね"
      ],
      "mega_ability": "かんつうドリル",
      "mega_ability_desc": "接触技で守り効果を無視し1/4ダメージ",
      "mega_stats": {
        "H": 110,
        "A": 165,
        "B": 100,
        "C": 65,
        "D": 65,
        "S": 103
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_chandelure",
      "name": "シャンデナイト",
      "name_en": "Chandelureite",
      "category": "mega_stone",
      "effect": "シャンデラ を メガシャンデラ にメガシンカさせる (戦闘中1回)",
      "applies_to": "シャンデラ",
      "restriction": "シャンデラ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガシャンデラ",
      "mega_target_en": "Chandelure",
      "mega_types": [
        "ほのお",
        "ゴースト"
      ],
      "mega_ability": "すりぬけ",
      "mega_ability_desc": "相手のリフレクター等を無視",
      "mega_stats": {
        "H": 60,
        "A": 75,
        "B": 110,
        "C": 175,
        "D": 110,
        "S": 90
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_golurk",
      "name": "ゴルーグナイト",
      "name_en": "Golurkite",
      "category": "mega_stone",
      "effect": "ゴルーグ を メガゴルーグ にメガシンカさせる (戦闘中1回)",
      "applies_to": "ゴルーグ",
      "restriction": "ゴルーグ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガゴルーグ",
      "mega_target_en": "Golurk",
      "mega_types": [
        "じめん",
        "ゴースト"
      ],
      "mega_ability": "ふかしのこぶし",
      "mega_ability_desc": "接触技が守り効果を受けない",
      "mega_stats": {
        "H": 89,
        "A": 159,
        "B": 105,
        "C": 70,
        "D": 105,
        "S": 55
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_chesnaught",
      "name": "ブリガロンナイト",
      "name_en": "Chesnaughtite",
      "category": "mega_stone",
      "effect": "ブリガロン を メガブリガロン にメガシンカさせる (戦闘中1回)",
      "applies_to": "ブリガロン",
      "restriction": "ブリガロン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "za_link",
      "acquisition_note": "ポケモンZA連携 (HOME 経由)",
      "mega_form": "メガブリガロン",
      "mega_target_en": "Chesnaught",
      "mega_types": [
        "くさ",
        "あく"
      ],
      "mega_ability": "ぼうだん",
      "mega_ability_desc": "たま・爆弾系技を無効化",
      "mega_stats": {
        "H": 89,
        "A": 137,
        "B": 172,
        "C": 74,
        "D": 115,
        "S": 44
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia は タイプ=くさ/かくとう (従来仕様) と表記。攻略大百科の くさ/あく を採用"
    },
    {
      "key": "mega_stone_delphox",
      "name": "マフォクシナイト",
      "name_en": "Delphoxite",
      "category": "mega_stone",
      "effect": "マフォクシー を メガマフォクシー にメガシンカさせる (戦闘中1回)",
      "applies_to": "マフォクシー",
      "restriction": "マフォクシー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "za_link",
      "acquisition_note": "ポケモンZA連携 (HOME 経由)",
      "mega_form": "メガマフォクシー",
      "mega_target_en": "Delphox",
      "mega_types": [
        "エスパー",
        "フェアリー"
      ],
      "mega_ability": "ふゆう",
      "mega_ability_desc": "じめん技・フィールド効果を受けない",
      "mega_stats": {
        "H": 75,
        "A": 69,
        "B": 72,
        "C": 159,
        "D": 125,
        "S": 134
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia/アルテマ は タイプ=ほのお/エスパー (従来仕様) と表記。攻略大百科の エスパー/フェアリー を採用"
    },
    {
      "key": "mega_stone_greninja",
      "name": "ゲッコウガナイト",
      "name_en": "Greninjaite",
      "category": "mega_stone",
      "effect": "ゲッコウガ を メガゲッコウガ にメガシンカさせる (戦闘中1回)",
      "applies_to": "ゲッコウガ",
      "restriction": "ゲッコウガ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "za_link",
      "acquisition_note": "ポケモンZA連携 (HOME 経由)",
      "mega_form": "メガゲッコウガ",
      "mega_target_en": "Greninja",
      "mega_types": [
        "みず",
        "あく"
      ],
      "mega_ability": "へんげんじざい",
      "mega_ability_desc": "初回技で出す技と同じタイプに変化",
      "mega_stats": {
        "H": 72,
        "A": 125,
        "B": 77,
        "C": 133,
        "D": 81,
        "S": 142
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_floette",
      "name": "フラエッテナイト",
      "name_en": "Floetteite",
      "category": "mega_stone",
      "effect": "フラエッテ(えいえんのはな) を メガフラエッテ にメガシンカさせる (戦闘中1回)",
      "applies_to": "フラエッテ(えいえんのはな)",
      "restriction": "フラエッテ(えいえんのはな) のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "za_link",
      "acquisition_note": "ポケモンZA連携 (HOME 経由)",
      "mega_form": "メガフラエッテ",
      "mega_target_en": "Floette",
      "mega_types": [
        "フェアリー"
      ],
      "mega_ability": "フェアリーオーラ",
      "mega_ability_desc": "全員のフェアリー技の威力 4/3倍 (1.33倍)",
      "mega_stats": {
        "H": 74,
        "A": 85,
        "B": 87,
        "C": 155,
        "D": 148,
        "S": 102
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "倍率は 4/3 = 約1.33倍 (攻略大百科は 4/3 表記、AppMedia は 1.33倍 表記で同義)"
    },
    {
      "key": "mega_stone_meowstic",
      "name": "ニャオニクスナイト",
      "name_en": "Meowsticite",
      "category": "mega_stone",
      "effect": "ニャオニクス を メガニャオニクス にメガシンカさせる (戦闘中1回)",
      "applies_to": "ニャオニクス",
      "restriction": "ニャオニクス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガニャオニクス",
      "mega_target_en": "Meowstic",
      "mega_types": [
        "エスパー"
      ],
      "mega_ability": "トレース",
      "mega_ability_desc": "場に出た時、相手の特性をコピー",
      "mega_stats": {
        "H": 74,
        "A": 48,
        "B": 76,
        "C": 143,
        "D": 101,
        "S": 124
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_hawlucha",
      "name": "ルチャブルナイト",
      "name_en": "Hawluchaite",
      "category": "mega_stone",
      "effect": "ルチャブル を メガルチャブル にメガシンカさせる (戦闘中1回)",
      "applies_to": "ルチャブル",
      "restriction": "ルチャブル のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガルチャブル",
      "mega_target_en": "Hawlucha",
      "mega_types": [
        "フェアリー",
        "ドラゴン"
      ],
      "mega_ability": "ノーガード",
      "mega_ability_desc": "技が必中になる (命中率の影響なし)",
      "mega_stats": {
        "H": 78,
        "A": 137,
        "B": 100,
        "C": 74,
        "D": 93,
        "S": 118
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia は タイプ=かくとう/ひこう (従来仕様) と表記。攻略大百科の フェアリー/ドラゴン を採用"
    },
    {
      "key": "mega_stone_crabominable",
      "name": "ケケンカニナイト",
      "name_en": "Crabominableite",
      "category": "mega_stone",
      "effect": "ケケンカニ を メガケケンカニ にメガシンカさせる (戦闘中1回)",
      "applies_to": "ケケンカニ",
      "restriction": "ケケンカニ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガケケンカニ",
      "mega_target_en": "Crabominable",
      "mega_types": [
        "みず",
        "かくとう"
      ],
      "mega_ability": "てつのこぶし",
      "mega_ability_desc": "パンチ系技の威力1.2倍",
      "mega_stats": {
        "H": 97,
        "A": 157,
        "B": 122,
        "C": 62,
        "D": 107,
        "S": 33
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": ""
    },
    {
      "key": "mega_stone_drampa",
      "name": "ジジーロンナイト",
      "name_en": "Drampaite",
      "category": "mega_stone",
      "effect": "ジジーロン を メガジジーロン にメガシンカさせる (戦闘中1回)",
      "applies_to": "ジジーロン",
      "restriction": "ジジーロン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガジジーロン",
      "mega_target_en": "Drampa",
      "mega_types": [
        "エスパー",
        "ドラゴン"
      ],
      "mega_ability": "ぎゃくじょう",
      "mega_ability_desc": "HP1/2以下になると特攻+1",
      "mega_stats": {
        "H": 78,
        "A": 85,
        "B": 110,
        "C": 160,
        "D": 116,
        "S": 36
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia は タイプ=ノーマル/ドラゴン (従来仕様) と表記。攻略大百科の エスパー/ドラゴン を採用"
    },
    {
      "key": "mega_stone_scovillain",
      "name": "スコヴィラナイト",
      "name_en": "Scovillainite",
      "category": "mega_stone",
      "effect": "スコヴィラン を メガスコヴィラン にメガシンカさせる (戦闘中1回)",
      "applies_to": "スコヴィラン",
      "restriction": "スコヴィラン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガスコヴィラン",
      "mega_target_en": "Scovillain",
      "mega_types": [
        "あく",
        "でんき"
      ],
      "mega_ability": "とびだすハバネロ",
      "mega_ability_desc": "技ダメージを受けるとやけど状態にする",
      "mega_stats": {
        "H": 65,
        "A": 138,
        "B": 85,
        "C": 138,
        "D": 85,
        "S": 75
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia は タイプ=くさ/ほのお (従来仕様) と表記。攻略大百科の あく/でんき を採用"
    },
    {
      "key": "mega_stone_glimmora",
      "name": "キラフロナイト",
      "name_en": "Glimmoraite",
      "category": "mega_stone",
      "effect": "キラフロル を メガキラフロル にメガシンカさせる (戦闘中1回)",
      "applies_to": "キラフロル",
      "restriction": "キラフロル のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガキラフロル",
      "mega_target_en": "Glimmora",
      "mega_types": [
        "エスパー",
        "フェアリー"
      ],
      "mega_ability": "てきおうりょく",
      "mega_ability_desc": "同じタイプ技のダメージが1.5倍→2倍",
      "mega_stats": {
        "H": 83,
        "A": 90,
        "B": 105,
        "C": 150,
        "D": 96,
        "S": 101
      },
      "source": "items_data_pokechan.md 7-3 (攻略大百科ベース、不一致は notes 参照)",
      "verify": false,
      "notes": "AppMedia は タイプ=いわ/どく (従来仕様) と表記。攻略大百科の エスパー/フェアリー を採用"
    },
    {
      "key": "mega_stone_beedrill",
      "name": "スピアナイト",
      "name_en": "Beedrillite",
      "category": "mega_stone",
      "effect": "スピアー をメガシンカさせる (戦闘中1回)",
      "applies_to": "スピアー",
      "restriction": "スピアー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "tutorial_free",
      "acquisition_note": "バトルチュートリアル報酬 (無料)",
      "mega_form": "メガスピアー",
      "mega_target_en": "Beedrill",
      "mega_types": [
        "むし",
        "どく"
      ],
      "mega_ability": "スナイパー",
      "mega_ability_desc": "急所に当たった時、技の威力が通常の1.5倍ではなく2.25倍になる",
      "mega_stats": {
        "H": 65,
        "A": 150,
        "B": 40,
        "C": 15,
        "D": 80,
        "S": 145
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_manectric",
      "name": "ライボルトナイト",
      "name_en": "Manectricite",
      "category": "mega_stone",
      "effect": "ライボルト をメガシンカさせる (戦闘中1回)",
      "applies_to": "ライボルト",
      "restriction": "ライボルト のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "tutorial_free",
      "acquisition_note": "バトルチュートリアル報酬 (無料)",
      "mega_form": "メガライボルト",
      "mega_target_en": "Manectric",
      "mega_types": [
        "でんき"
      ],
      "mega_ability": "ひらいしん",
      "mega_ability_desc": "場の全てのでんき技を自分に集める。受けたでんき技は無効化し、特攻が1段階上がる",
      "mega_stats": {
        "H": 70,
        "A": 75,
        "B": 80,
        "C": 135,
        "D": 80,
        "S": 135
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_gyarados",
      "name": "ギャラドスナイト",
      "name_en": "Gyaradosite",
      "category": "mega_stone",
      "effect": "ギャラドス をメガシンカさせる (戦闘中1回)",
      "applies_to": "ギャラドス",
      "restriction": "ギャラドス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "tutorial_free",
      "acquisition_note": "バトルチュートリアル報酬 (無料)",
      "mega_form": "メガギャラドス",
      "mega_target_en": "Gyarados",
      "mega_types": [
        "みず",
        "あく"
      ],
      "mega_ability": "かたやぶり",
      "mega_ability_desc": "相手の特性を無視して技を出せる",
      "mega_stats": {
        "H": 95,
        "A": 155,
        "B": 109,
        "C": 70,
        "D": 130,
        "S": 81
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_garchomp",
      "name": "ガブリアスナイト",
      "name_en": "Garchompite",
      "category": "mega_stone",
      "effect": "ガブリアス をメガシンカさせる (戦闘中1回)",
      "applies_to": "ガブリアス",
      "restriction": "ガブリアス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "tutorial_free",
      "acquisition_note": "バトルチュートリアル報酬 (無料)",
      "mega_form": "メガガブリアス",
      "mega_target_en": "Garchomp",
      "mega_types": [
        "ドラゴン",
        "じめん"
      ],
      "mega_ability": "すなのちから",
      "mega_ability_desc": "すなあらし時、いわ・じめん・はがね技の威力が1.3倍になる。すなあらしのダメージを受けない",
      "mega_stats": {
        "H": 108,
        "A": 170,
        "B": 115,
        "C": 120,
        "D": 95,
        "S": 92
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_steelix",
      "name": "ハガネールナイト",
      "name_en": "Steelixite",
      "category": "mega_stone",
      "effect": "ハガネール をメガシンカさせる (戦闘中1回)",
      "applies_to": "ハガネール",
      "restriction": "ハガネール のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "tutorial_free",
      "acquisition_note": "バトルチュートリアル報酬 (無料)",
      "mega_form": "メガハガネール",
      "mega_target_en": "Steelix",
      "mega_types": [
        "はがね",
        "じめん"
      ],
      "mega_ability": "すなのちから",
      "mega_ability_desc": "すなあらし時、いわ・じめん・はがね技の威力が1.3倍になる。すなあらしのダメージを受けない",
      "mega_stats": {
        "H": 75,
        "A": 125,
        "B": 230,
        "C": 55,
        "D": 95,
        "S": 30
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_heracross",
      "name": "ヘラクロスナイト",
      "name_en": "Heracrossite",
      "category": "mega_stone",
      "effect": "ヘラクロス をメガシンカさせる (戦闘中1回)",
      "applies_to": "ヘラクロス",
      "restriction": "ヘラクロス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "tutorial_free",
      "acquisition_note": "バトルチュートリアル報酬 (無料)",
      "mega_form": "メガヘラクロス",
      "mega_target_en": "Heracross",
      "mega_types": [
        "むし",
        "かくとう"
      ],
      "mega_ability": "スキルリンク",
      "mega_ability_desc": "連続技を必ず最大回数(主に5回)出せる",
      "mega_stats": {
        "H": 80,
        "A": 185,
        "B": 115,
        "C": 40,
        "D": 105,
        "S": 75
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_aggron",
      "name": "ボスゴドラナイト",
      "name_en": "Aggronite",
      "category": "mega_stone",
      "effect": "ボスゴドラ をメガシンカさせる (戦闘中1回)",
      "applies_to": "ボスゴドラ",
      "restriction": "ボスゴドラ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "tutorial_free",
      "acquisition_note": "バトルチュートリアル報酬 (無料)",
      "mega_form": "メガボスゴドラ",
      "mega_target_en": "Aggron",
      "mega_types": [
        "はがね"
      ],
      "mega_ability": "フィルター",
      "mega_ability_desc": "効果ばつぐんの技で受けるダメージが0.75倍に軽減される",
      "mega_stats": {
        "H": 70,
        "A": 140,
        "B": 230,
        "C": 60,
        "D": 80,
        "S": 50
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_abomasnow",
      "name": "ユキノオーナイト",
      "name_en": "Abomasnowite",
      "category": "mega_stone",
      "effect": "ユキノオー をメガシンカさせる (戦闘中1回)",
      "applies_to": "ユキノオー",
      "restriction": "ユキノオー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "tutorial_free",
      "acquisition_note": "バトルチュートリアル報酬 (無料)",
      "mega_form": "メガユキノオー",
      "mega_target_en": "Abomasnow",
      "mega_types": [
        "くさ",
        "こおり"
      ],
      "mega_ability": "ゆきふらし",
      "mega_ability_desc": "場に出ると天候が「ゆき」になる(5ターン)",
      "mega_stats": {
        "H": 90,
        "A": 132,
        "B": 105,
        "C": 132,
        "D": 105,
        "S": 30
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_venusaur",
      "name": "フシギバナイト",
      "name_en": "Venusaurite",
      "category": "mega_stone",
      "effect": "フシギバナ をメガシンカさせる (戦闘中1回)",
      "applies_to": "フシギバナ",
      "restriction": "フシギバナ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガフシギバナ",
      "mega_target_en": "Venusaur",
      "mega_types": [
        "くさ",
        "どく"
      ],
      "mega_ability": "あついしぼう",
      "mega_ability_desc": "ほのお技・こおり技で受けるダメージが半減になる",
      "mega_stats": {
        "H": 80,
        "A": 100,
        "B": 123,
        "C": 122,
        "D": 120,
        "S": 80
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_charizard_x",
      "name": "リザードナイトX",
      "name_en": "CharizarditeX",
      "category": "mega_stone",
      "effect": "リザードン をメガシンカさせる (戦闘中1回)",
      "applies_to": "リザードン",
      "restriction": "リザードン のみ装備可能 (X)",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガリザードンX",
      "mega_target_en": "Charizard X",
      "mega_types": [
        "ほのお",
        "ドラゴン"
      ],
      "mega_ability": "かたいツメ",
      "mega_ability_desc": "接触する技の威力が1.3倍になる",
      "mega_stats": {
        "H": 78,
        "A": 130,
        "B": 111,
        "C": 130,
        "D": 85,
        "S": 100
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_charizard_y",
      "name": "リザードナイトY",
      "name_en": "CharizarditeY",
      "category": "mega_stone",
      "effect": "リザードン をメガシンカさせる (戦闘中1回)",
      "applies_to": "リザードン",
      "restriction": "リザードン のみ装備可能 (Y)",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガリザードンY",
      "mega_target_en": "Charizard Y",
      "mega_types": [
        "ほのお",
        "ひこう"
      ],
      "mega_ability": "ひでり",
      "mega_ability_desc": "場に出ると天候が「ひざしのつよい」になる(5ターン)",
      "mega_stats": {
        "H": 78,
        "A": 104,
        "B": 78,
        "C": 159,
        "D": 115,
        "S": 100
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_blastoise",
      "name": "カメックスナイト",
      "name_en": "Blastoiseite",
      "category": "mega_stone",
      "effect": "カメックス をメガシンカさせる (戦闘中1回)",
      "applies_to": "カメックス",
      "restriction": "カメックス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガカメックス",
      "mega_target_en": "Blastoise",
      "mega_types": [
        "みず"
      ],
      "mega_ability": "メガランチャー",
      "mega_ability_desc": "波動技(はどうだん・あくのはどう等)の威力が1.5倍になる",
      "mega_stats": {
        "H": 79,
        "A": 103,
        "B": 120,
        "C": 135,
        "D": 115,
        "S": 78
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_pidgeot",
      "name": "ピジョットナイト",
      "name_en": "Pidgeotite",
      "category": "mega_stone",
      "effect": "ピジョット をメガシンカさせる (戦闘中1回)",
      "applies_to": "ピジョット",
      "restriction": "ピジョット のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガピジョット",
      "mega_target_en": "Pidgeot",
      "mega_types": [
        "ノーマル",
        "ひこう"
      ],
      "mega_ability": "ノーガード",
      "mega_ability_desc": "自分と相手の出す技が必ず命中する",
      "mega_stats": {
        "H": 83,
        "A": 80,
        "B": 80,
        "C": 135,
        "D": 80,
        "S": 121
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_gengar",
      "name": "ゲンガナイト",
      "name_en": "Gengarite",
      "category": "mega_stone",
      "effect": "ゲンガー をメガシンカさせる (戦闘中1回)",
      "applies_to": "ゲンガー",
      "restriction": "ゲンガー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガゲンガー",
      "mega_target_en": "Gengar",
      "mega_types": [
        "ゴースト",
        "どく"
      ],
      "mega_ability": "かげふみ",
      "mega_ability_desc": "相手の交代・逃げを封じる",
      "mega_stats": {
        "H": 60,
        "A": 65,
        "B": 80,
        "C": 170,
        "D": 95,
        "S": 130
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_kangaskhan",
      "name": "ガルーラナイト",
      "name_en": "Kangaskhanite",
      "category": "mega_stone",
      "effect": "ガルーラ をメガシンカさせる (戦闘中1回)",
      "applies_to": "ガルーラ",
      "restriction": "ガルーラ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガガルーラ",
      "mega_target_en": "Kangaskhan",
      "mega_types": [
        "ノーマル"
      ],
      "mega_ability": "おやこあい",
      "mega_ability_desc": "1ターンに親と子で2回攻撃する。2回目の威力は減少する",
      "mega_stats": {
        "H": 105,
        "A": 125,
        "B": 100,
        "C": 60,
        "D": 100,
        "S": 100
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_lucario",
      "name": "ルカリオナイト",
      "name_en": "Lucarioite",
      "category": "mega_stone",
      "effect": "ルカリオ をメガシンカさせる (戦闘中1回)",
      "applies_to": "ルカリオ",
      "restriction": "ルカリオ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガルカリオ",
      "mega_target_en": "Lucario",
      "mega_types": [
        "かくとう",
        "はがね"
      ],
      "mega_ability": "てきおうりょく",
      "mega_ability_desc": "同じタイプの技を出すとダメージが1.5倍ではなく2倍になる",
      "mega_stats": {
        "H": 70,
        "A": 145,
        "B": 88,
        "C": 140,
        "D": 70,
        "S": 112
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_lopunny",
      "name": "ミミロップナイト",
      "name_en": "Lopunnyite",
      "category": "mega_stone",
      "effect": "ミミロップ をメガシンカさせる (戦闘中1回)",
      "applies_to": "ミミロップ",
      "restriction": "ミミロップ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガミミロップ",
      "mega_target_en": "Lopunny",
      "mega_types": [
        "ノーマル",
        "かくとう"
      ],
      "mega_ability": "じゅうなん",
      "mega_ability_desc": "まひ状態にならない",
      "mega_stats": {
        "H": 65,
        "A": 136,
        "B": 94,
        "C": 54,
        "D": 96,
        "S": 135
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_gardevoir",
      "name": "サーナイトナイト",
      "name_en": "Gardevoirite",
      "category": "mega_stone",
      "effect": "サーナイト をメガシンカさせる (戦闘中1回)",
      "applies_to": "サーナイト",
      "restriction": "サーナイト のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガサーナイト",
      "mega_target_en": "Gardevoir",
      "mega_types": [
        "エスパー",
        "フェアリー"
      ],
      "mega_ability": "フェアリースキン",
      "mega_ability_desc": "ノーマル技がフェアリータイプに変わり、威力が1.2倍になる",
      "mega_stats": {
        "H": 68,
        "A": 85,
        "B": 65,
        "C": 165,
        "D": 135,
        "S": 100
      },
      "source": "標準メガシンカ仕様 (Gen6/7 Bulbapedia/Serebii/攻略大百科で一致)",
      "verify": true,
      "notes": "標準データ。ポケチャン版で独自仕様 (タイプ/特性/種族値の変更) がある可能性があるためゲーム内要確認"
    },
    {
      "key": "mega_stone_absol",
      "name": "アブソルナイト",
      "name_en": "Absolite",
      "category": "mega_stone",
      "effect": "アブソル を メガアブソル にメガシンカさせる (戦闘中1回)",
      "applies_to": "アブソル",
      "restriction": "アブソル のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "absolite",
      "mega_form": "メガアブソル",
      "mega_target_en": "Absol",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_aerodactyl",
      "name": "プテラナイト",
      "name_en": "Aerodactylite",
      "category": "mega_stone",
      "effect": "プテラ を メガプテラ にメガシンカさせる (戦闘中1回)",
      "applies_to": "プテラ",
      "restriction": "プテラ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "aerodactylite",
      "mega_form": "メガプテラ",
      "mega_target_en": "Aerodactyl",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_alakazam",
      "name": "フーディナイト",
      "name_en": "Alakazite",
      "category": "mega_stone",
      "effect": "フーディン を メガフーディン にメガシンカさせる (戦闘中1回)",
      "applies_to": "フーディン",
      "restriction": "フーディン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "alakazite",
      "mega_form": "メガフーディン",
      "mega_target_en": "Alakazam",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_altaria",
      "name": "チルタリスナイト",
      "name_en": "Altarianite",
      "category": "mega_stone",
      "effect": "チルタリス を メガチルタリス にメガシンカさせる (戦闘中1回)",
      "applies_to": "チルタリス",
      "restriction": "チルタリス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "altarianite",
      "mega_form": "メガチルタリス",
      "mega_target_en": "Altaria",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_ampharos",
      "name": "デンリュウナイト",
      "name_en": "Ampharosite",
      "category": "mega_stone",
      "effect": "デンリュウ を メガデンリュウ にメガシンカさせる (戦闘中1回)",
      "applies_to": "デンリュウ",
      "restriction": "デンリュウ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "ampharosite",
      "mega_form": "メガデンリュウ",
      "mega_target_en": "Ampharos",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_audino",
      "name": "タブンネナイト",
      "name_en": "Audinite",
      "category": "mega_stone",
      "effect": "タブンネ を メガタブンネ にメガシンカさせる (戦闘中1回)",
      "applies_to": "タブンネ",
      "restriction": "タブンネ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "audinite",
      "mega_form": "メガタブンネ",
      "mega_target_en": "Audino",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_banette",
      "name": "ジュペッタナイト",
      "name_en": "Banettite",
      "category": "mega_stone",
      "effect": "ジュペッタ を メガジュペッタ にメガシンカさせる (戦闘中1回)",
      "applies_to": "ジュペッタ",
      "restriction": "ジュペッタ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "banettite",
      "mega_form": "メガジュペッタ",
      "mega_target_en": "Banette",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_camerupt",
      "name": "バクーダナイト",
      "name_en": "Cameruptite",
      "category": "mega_stone",
      "effect": "バクーダ を メガバクーダ にメガシンカさせる (戦闘中1回)",
      "applies_to": "バクーダ",
      "restriction": "バクーダ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "cameruptite",
      "mega_form": "メガバクーダ",
      "mega_target_en": "Camerupt",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_gallade",
      "name": "エルレイドナイト",
      "name_en": "Galladite",
      "category": "mega_stone",
      "effect": "エルレイド を メガエルレイド にメガシンカさせる (戦闘中1回)",
      "applies_to": "エルレイド",
      "restriction": "エルレイド のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "galladite",
      "mega_form": "メガエルレイド",
      "mega_target_en": "Gallade",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_glalie",
      "name": "オニゴーリナイト",
      "name_en": "Glalitite",
      "category": "mega_stone",
      "effect": "オニゴーリ を メガオニゴーリ にメガシンカさせる (戦闘中1回)",
      "applies_to": "オニゴーリ",
      "restriction": "オニゴーリ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "glalitite",
      "mega_form": "メガオニゴーリ",
      "mega_target_en": "Glalie",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_houndoom",
      "name": "ヘルガナイト",
      "name_en": "Houndoominite",
      "category": "mega_stone",
      "effect": "ヘルガー を メガヘルガー にメガシンカさせる (戦闘中1回)",
      "applies_to": "ヘルガー",
      "restriction": "ヘルガー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "houndoominite",
      "mega_form": "メガヘルガー",
      "mega_target_en": "Houndoom",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_medicham",
      "name": "チャーレムナイト",
      "name_en": "Medichamite",
      "category": "mega_stone",
      "effect": "チャーレム を メガチャーレム にメガシンカさせる (戦闘中1回)",
      "applies_to": "チャーレム",
      "restriction": "チャーレム のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "medichamite",
      "mega_form": "メガチャーレム",
      "mega_target_en": "Medicham",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_pinsir",
      "name": "カイロスナイト",
      "name_en": "Pinsirite",
      "category": "mega_stone",
      "effect": "カイロス を メガカイロス にメガシンカさせる (戦闘中1回)",
      "applies_to": "カイロス",
      "restriction": "カイロス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "pinsirite",
      "mega_form": "メガカイロス",
      "mega_target_en": "Pinsir",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_sableye",
      "name": "ヤミラミナイト",
      "name_en": "Sablenite",
      "category": "mega_stone",
      "effect": "ヤミラミ を メガヤミラミ にメガシンカさせる (戦闘中1回)",
      "applies_to": "ヤミラミ",
      "restriction": "ヤミラミ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "sablenite",
      "mega_form": "メガヤミラミ",
      "mega_target_en": "Sableye",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_scizor",
      "name": "ハッサムナイト",
      "name_en": "Scizorite",
      "category": "mega_stone",
      "effect": "ハッサム を メガハッサム にメガシンカさせる (戦闘中1回)",
      "applies_to": "ハッサム",
      "restriction": "ハッサム のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "scizorite",
      "mega_form": "メガハッサム",
      "mega_target_en": "Scizor",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_sharpedo",
      "name": "サメハダナイト",
      "name_en": "Sharpedonite",
      "category": "mega_stone",
      "effect": "サメハダー を メガサメハダー にメガシンカさせる (戦闘中1回)",
      "applies_to": "サメハダー",
      "restriction": "サメハダー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "sharpedonite",
      "mega_form": "メガサメハダー",
      "mega_target_en": "Sharpedo",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_slowbro",
      "name": "ヤドランナイト",
      "name_en": "Slowbronite",
      "category": "mega_stone",
      "effect": "ヤドラン を メガヤドラン にメガシンカさせる (戦闘中1回)",
      "applies_to": "ヤドラン",
      "restriction": "ヤドラン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "slowbronite",
      "mega_form": "メガヤドラン",
      "mega_target_en": "Slowbro",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_tyranitar",
      "name": "バンギラスナイト",
      "name_en": "Tyranitarite",
      "category": "mega_stone",
      "effect": "バンギラス を メガバンギラス にメガシンカさせる (戦闘中1回)",
      "applies_to": "バンギラス",
      "restriction": "バンギラス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "pokeapi_slug": "tyranitarite",
      "mega_form": "メガバンギラス",
      "mega_target_en": "Tyranitar",
      "mega_types": [],
      "mega_ability": "",
      "mega_ability_desc": "",
      "mega_stats": {},
      "source": "PokeAPI (name 9言語取得済) + Serebii/Game8 (実装状況)",
      "verify": true,
      "notes": ""
    },
    {
      "key": "mega_stone_raichu_x",
      "name": "ライチュウナイトX",
      "name_en": "RaichuiteX",
      "category": "mega_stone",
      "effect": "メガライチュウXをメガシンカさせる (戦闘中1回)",
      "applies_to": "ライチュウ",
      "restriction": "ライチュウ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP_or_campaign",
      "acquisition_note": "フロンティアショップ 2,000VP / スマホ版配信キャンペーン(〜2026/9/2 10:59)でメール無料受取",
      "mega_form": "メガライチュウX",
      "mega_target_en": "Raichu X",
      "mega_types": [
        "でんき"
      ],
      "mega_ability": "エレキメイカー",
      "mega_ability_desc": "登場から5ターン、全体の場をエレキフィールド状態にする",
      "mega_stats": {
        "H": 60,
        "A": 135,
        "B": 95,
        "C": 90,
        "D": 95,
        "S": 110
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_raichu_y",
      "name": "ライチュウナイトY",
      "name_en": "RaichuiteY",
      "category": "mega_stone",
      "effect": "メガライチュウYをメガシンカさせる (戦闘中1回)",
      "applies_to": "ライチュウ",
      "restriction": "ライチュウ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP_or_campaign",
      "acquisition_note": "フロンティアショップ 2,000VP / スマホ版配信キャンペーンで無料受取",
      "mega_form": "メガライチュウY",
      "mega_target_en": "Raichu Y",
      "mega_types": [
        "でんき"
      ],
      "mega_ability": "ノーガード",
      "mega_ability_desc": "互いの技の命中率が100%になる",
      "mega_stats": {
        "H": 60,
        "A": 100,
        "B": 55,
        "C": 160,
        "D": 80,
        "S": 130
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_sceptile",
      "name": "ジュカイナイト",
      "name_en": "Sceptilite",
      "category": "mega_stone",
      "effect": "メガジュカインをメガシンカさせる (戦闘中1回)",
      "applies_to": "ジュカイン",
      "restriction": "ジュカイン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP / スタンダードセレクトM-Bスカウト",
      "mega_form": "メガジュカイン",
      "mega_target_en": "Sceptile",
      "mega_types": [
        "くさ",
        "ドラゴン"
      ],
      "mega_ability": "ひらいしん",
      "mega_ability_desc": "でんき技を引き寄せて無効化し、自身の特攻が1段階上がる",
      "mega_stats": {
        "H": 70,
        "A": 110,
        "B": 75,
        "C": 145,
        "D": 85,
        "S": 145
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_blaziken",
      "name": "バシャーモナイト",
      "name_en": "Blazikenite",
      "category": "mega_stone",
      "effect": "メガバシャーモをメガシンカさせる (戦闘中1回)",
      "applies_to": "バシャーモ",
      "restriction": "バシャーモ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガバシャーモ",
      "mega_target_en": "Blaziken",
      "mega_types": [
        "ほのお",
        "かくとう"
      ],
      "mega_ability": "かそく",
      "mega_ability_desc": "ターン終わりに素早さが1段階上がる",
      "mega_stats": {
        "H": 80,
        "A": 160,
        "B": 80,
        "C": 130,
        "D": 80,
        "S": 100
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_swampert",
      "name": "ラグラージナイト",
      "name_en": "Swampertite",
      "category": "mega_stone",
      "effect": "メガラグラージをメガシンカさせる (戦闘中1回)",
      "applies_to": "ラグラージ",
      "restriction": "ラグラージ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガラグラージ",
      "mega_target_en": "Swampert",
      "mega_types": [
        "みず",
        "じめん"
      ],
      "mega_ability": "すいすい",
      "mega_ability_desc": "あめ状態の時、素早さが2倍になる",
      "mega_stats": {
        "H": 100,
        "A": 150,
        "B": 110,
        "C": 95,
        "D": 110,
        "S": 70
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_mawile",
      "name": "クチートナイト",
      "name_en": "Mawilite",
      "category": "mega_stone",
      "effect": "メガクチートをメガシンカさせる (戦闘中1回)",
      "applies_to": "クチート",
      "restriction": "クチート のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガクチート",
      "mega_target_en": "Mawile",
      "mega_types": [
        "はがね",
        "フェアリー"
      ],
      "mega_ability": "ちからもち",
      "mega_ability_desc": "自分の物理技の威力が2倍になる",
      "mega_stats": {
        "H": 50,
        "A": 105,
        "B": 125,
        "C": 55,
        "D": 95,
        "S": 50
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_metagross",
      "name": "メタグロスナイト",
      "name_en": "Metagrossite",
      "category": "mega_stone",
      "effect": "メガメタグロスをメガシンカさせる (戦闘中1回)",
      "applies_to": "メタグロス",
      "restriction": "メタグロス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガメタグロス",
      "mega_target_en": "Metagross",
      "mega_types": [
        "はがね",
        "エスパー"
      ],
      "mega_ability": "かたいツメ",
      "mega_ability_desc": "接触する技の威力が1.3倍になる",
      "mega_stats": {
        "H": 80,
        "A": 145,
        "B": 150,
        "C": 105,
        "D": 110,
        "S": 110
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_staraptor",
      "name": "ムクホークナイト",
      "name_en": "Staraptite",
      "category": "mega_stone",
      "effect": "メガムクホークをメガシンカさせる (戦闘中1回)",
      "applies_to": "ムクホーク",
      "restriction": "ムクホーク のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガムクホーク",
      "mega_target_en": "Staraptor",
      "mega_types": [
        "かくとう",
        "ひこう"
      ],
      "mega_ability": "あまのじゃく",
      "mega_ability_desc": "能力ランクの変化が逆になる",
      "mega_stats": {
        "H": 85,
        "A": 140,
        "B": 100,
        "C": 60,
        "D": 90,
        "S": 110
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_scolipede",
      "name": "ペンドラナイト",
      "name_en": "Scolipite",
      "category": "mega_stone",
      "effect": "メガペンドラーをメガシンカさせる (戦闘中1回)",
      "applies_to": "ペンドラー",
      "restriction": "ペンドラー のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガペンドラー",
      "mega_target_en": "Scolipede",
      "mega_types": [
        "むし",
        "どく"
      ],
      "mega_ability": "シェルアーマー",
      "mega_ability_desc": "相手の攻撃が急所に当たらない",
      "mega_stats": {
        "H": 60,
        "A": 140,
        "B": 149,
        "C": 75,
        "D": 99,
        "S": 62
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_scrafty",
      "name": "ズルズキンナイト",
      "name_en": "Scraftinite",
      "category": "mega_stone",
      "effect": "メガズルズキンをメガシンカさせる (戦闘中1回)",
      "applies_to": "ズルズキン",
      "restriction": "ズルズキン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガズルズキン",
      "mega_target_en": "Scrafty",
      "mega_types": [
        "あく",
        "かくとう"
      ],
      "mega_ability": "いかく",
      "mega_ability_desc": "登場時に相手の攻撃を1段階下げる",
      "mega_stats": {
        "H": 65,
        "A": 130,
        "B": 135,
        "C": 55,
        "D": 135,
        "S": 68
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_eelektross",
      "name": "シビルドナイト",
      "name_en": "Eelektrossite",
      "category": "mega_stone",
      "effect": "メガシビルドンをメガシンカさせる (戦闘中1回)",
      "applies_to": "シビルドン",
      "restriction": "シビルドン のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガシビルドン",
      "mega_target_en": "Eelektross",
      "mega_types": [
        "でんき"
      ],
      "mega_ability": "うなぎのぼり",
      "mega_ability_desc": "地面にいないことになりじめん技/まきびし/どくびし/ねばねばネット無効。相手を倒すと最も高い能力ランク+1",
      "mega_stats": {
        "H": 85,
        "A": 145,
        "B": 80,
        "C": 135,
        "D": 90,
        "S": 80
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_pyroar",
      "name": "カエンジシナイト",
      "name_en": "Pyroarite",
      "category": "mega_stone",
      "effect": "メガカエンジシをメガシンカさせる (戦闘中1回)",
      "applies_to": "カエンジシ",
      "restriction": "カエンジシ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガカエンジシ",
      "mega_target_en": "Pyroar",
      "mega_types": [
        "ほのお",
        "ノーマル"
      ],
      "mega_ability": "ほのおのたてがみ",
      "mega_ability_desc": "ほのお技の威力が1.5倍になる",
      "mega_stats": {
        "H": 86,
        "A": 78,
        "B": 92,
        "C": 129,
        "D": 96,
        "S": 126
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_malamar",
      "name": "カラマネロナイト",
      "name_en": "Malamarite",
      "category": "mega_stone",
      "effect": "メガカラマネロをメガシンカさせる (戦闘中1回)",
      "applies_to": "カラマネロ",
      "restriction": "カラマネロ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガカラマネロ",
      "mega_target_en": "Malamar",
      "mega_types": [
        "あく",
        "エスパー"
      ],
      "mega_ability": "あまのじゃく",
      "mega_ability_desc": "能力ランクの変化が逆になる",
      "mega_stats": {
        "H": 86,
        "A": 102,
        "B": 88,
        "C": 98,
        "D": 120,
        "S": 88
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_barbaracle",
      "name": "ガメノデスナイト",
      "name_en": "Barbaracite",
      "category": "mega_stone",
      "effect": "メガガメノデスをメガシンカさせる (戦闘中1回)",
      "applies_to": "ガメノデス",
      "restriction": "ガメノデス のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガガメノデス",
      "mega_target_en": "Barbaracle",
      "mega_types": [
        "いわ",
        "かくとう"
      ],
      "mega_ability": "かたいツメ",
      "mega_ability_desc": "接触する技の威力が1.3倍になる",
      "mega_stats": {
        "H": 72,
        "A": 140,
        "B": 130,
        "C": 78,
        "D": 106,
        "S": 88
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_dragalge",
      "name": "ドラミドロナイト",
      "name_en": "Dragalgite",
      "category": "mega_stone",
      "effect": "メガドラミドロをメガシンカさせる (戦闘中1回)",
      "applies_to": "ドラミドロ",
      "restriction": "ドラミドロ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガドラミドロ",
      "mega_target_en": "Dragalge",
      "mega_types": [
        "どく",
        "ドラゴン"
      ],
      "mega_ability": "さいせいりょく",
      "mega_ability_desc": "手持ちに戻ると最大HPの1/3を回復する",
      "mega_stats": {
        "H": 65,
        "A": 85,
        "B": 105,
        "C": 132,
        "D": 163,
        "S": 44
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "mega_stone_falinks",
      "name": "タイレーツナイト",
      "name_en": "Falinksite",
      "category": "mega_stone",
      "effect": "メガタイレーツをメガシンカさせる (戦闘中1回)",
      "applies_to": "タイレーツ",
      "restriction": "タイレーツ のみ装備可能",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop_2000VP",
      "acquisition_note": "フロンティアショップ 2,000VP",
      "mega_form": "メガタイレーツ",
      "mega_target_en": "Falinks",
      "mega_types": [
        "かくとう"
      ],
      "mega_ability": "まけんき",
      "mega_ability_desc": "能力ランクが下がると攻撃を2段階上げる",
      "mega_stats": {
        "H": 65,
        "A": 135,
        "B": 135,
        "C": 70,
        "D": 90,
        "S": 105
      },
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "metronome",
      "name": "メトロノーム",
      "name_en": "Metronome",
      "category": "attack_boost",
      "effect": "同じ技を連続で使うと威力が20%ずつ上昇。最大100%上昇(2倍)",
      "factor": 1.2,
      "q12": 4915,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "ooki_na_nekko",
      "name": "おおきなねっこ",
      "name_en": "Big Root",
      "category": "hp_drain",
      "effect": "HP吸収技で回復するHP量が1.3倍になる",
      "factor": 1.3,
      "q12": 5325,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "koukaku_lens",
      "name": "こうかくレンズ",
      "name_en": "Wide Lens",
      "category": "misc",
      "effect": "技の命中率が1.1倍になる",
      "factor": 1.1,
      "q12": 4506,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "focus_lens",
      "name": "フォーカスレンズ",
      "name_en": "Zoom Lens",
      "category": "misc",
      "effect": "相手より遅く攻撃したとき技の命中率が1.2倍になる",
      "factor": 1.2,
      "q12": 4915,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "hikari_no_nendo",
      "name": "ひかりのねんど",
      "name_en": "Light Clay",
      "category": "misc",
      "effect": "ひかりのかべ・リフレクター・オーロラベールの効果が3ターン延長される(合計8ターン)",
      "factor": null,
      "q12": null,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 1,000VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "atsui_iwa",
      "name": "あついいわ",
      "name_en": "Heat Rock",
      "category": "misc",
      "effect": "天気「ひでり」「にほんばれ」の効果が3ターン延長される(合計8ターン)",
      "factor": null,
      "q12": null,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "sarasara_iwa",
      "name": "さらさらいわ",
      "name_en": "Smooth Rock",
      "category": "misc",
      "effect": "天気「すなあらし」の効果が3ターン延長される(合計8ターン)",
      "factor": null,
      "q12": null,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "shimetta_iwa",
      "name": "しめったいわ",
      "name_en": "Damp Rock",
      "category": "misc",
      "effect": "天気「あめ」の効果が3ターン延長される(合計8ターン)",
      "factor": null,
      "q12": null,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "tsumetai_iwa",
      "name": "つめたいいわ",
      "name_en": "Icy Rock",
      "category": "misc",
      "effect": "天気「ゆき」の効果が3ターン延長される(合計8ターン)",
      "factor": null,
      "q12": null,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "kireina_nukegara",
      "name": "きれいなぬけがら",
      "name_en": "Shed Shell",
      "category": "survival",
      "effect": "こうそくスピン等による交代封じを無視して必ず控えポケモンと交代できる",
      "factor": null,
      "q12": null,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 700VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    },
    {
      "key": "kuroi_tekkyu",
      "name": "くろいてっきゅう",
      "name_en": "Iron Ball",
      "category": "speed_boost",
      "effect": "装備者の素早さが半分になる。ひこうタイプ・ふゆう特性持ちにも地面タイプの技が当たるようになる",
      "factor": 0.5,
      "q12": 2048,
      "source_q12": "spec_pokemon_main",
      "implemented_in_pokechan": true,
      "acquisition": "frontier_shop",
      "acquisition_note": "フロンティアショップ 1,000VP",
      "source": "regulation_mb_2026-06 (GameWith/game8/AppMedia/Bulbapedia 等)",
      "verify": false,
      "notes": "レギュレーションM-B(2026-06-17〜09-02)で追加・実装確認済"
    }
  ],
  "stats": {
    "total_items": 132,
    "implemented_in_pokechan_true": 100,
    "implemented_in_pokechan_false": 14,
    "with_q12_value": 46,
    "with_verify_true": 23,
    "mega_stone_total": 42,
    "mega_stone_detailed": 23,
    "mega_stone_skeleton_verify_true": 18,
    "mega_stone_count": 60
  },
  "todo": [
    "ふうせん・くろいヘドロ・パンチグローブ等の verify:true 項目をゲーム内で確認",
    "メンタルハーブの効果説明をゲーム内テキストで確定",
    "ホズのみ (ノーマル半減) のポケチャンでの挙動確認",
    "メガストーン skeleton 18種 (チュートリアル8/フロンティアショップ旧来10) のメガ後タイプ・特性・種族値を追加リサーチ",
    "メガストーン「未実装確認済み」(2026-05-17, アルテマ未実装アイテム一覧より): メガミュウツーX / メガミュウツーY / メガレックウザ / メガラティオス / メガラティアス / メガバンギラス / メガヤドラン / メガアブソル / メガフーディン / メガジュペッタ / メガサメハダー / メガクチート / メガデンリュウ / メガプテラ / メガヤミラミ / メガチャーレム / メガラグラージ / メガジュカイン / メガバシャーモ / メガディアンシー / メガミュウ — これらはポケチャン未実装と確認できたため items_database には追加しない。今後ポケチャンに実装された際に追加する。"
  ],
  "regulation_mb": {
    "active_period": "2026-06-17 〜 2026-09-02 10:59",
    "rules": [
      "1回の対戦でメガシンカは1度のみ",
      "チームに複数のメガストーンを持たせることは可能",
      "メガシンカは技選択と同時にRボタンで発動",
      "メガ後の形態は対戦終了まで維持"
    ]
  }
};
