// Auto-generated by tools/_build_preset_builds_js.js — 手で編集しない。
// 元データ: reference/preset_builds_draft_v2.json (実戦58構築プリセット・2026-07-11)
// real_battle.html / online_battle.html が相手(AI)チーム生成に使う。
// 生成: 2026-07-11T06:17:14.375Z
window.PRESET_BUILDS = [
  {
    "id": 1,
    "species": "ガブリアス",
    "ability": "さめはだ",
    "nature": "いじっぱり",
    "ev": {
      "hp": 0,
      "atk": 32,
      "def": 2,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "きあいのタスキ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "じしん",
      "スケイルショット",
      "ステルスロック",
      "つるぎのまい"
    ],
    "role": "さめはだで直接当たってきた相手にダメージを返しつつ、きあいのタスキで一度はたえる。つるぎのまいで積んでからスケイルショットで連続こうげきする",
    "evidence_n": 139
  },
  {
    "id": 2,
    "species": "ミミッキュ",
    "ability": "ばけのかわ",
    "nature": "いじっぱり",
    "ev": {
      "hp": 29,
      "atk": 26,
      "def": 11,
      "spatk": 0,
      "spdef": 0,
      "spd": 0
    },
    "item": "いのちのたま",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "じゃれつく",
      "かげうち",
      "つるぎのまい",
      "シャドークロー"
    ],
    "role": "ばけのかわで一回だけこうげきを無効にしつつ、つるぎのまいで積んでから暴れまわる",
    "evidence_n": 107
  },
  {
    "id": 3,
    "species": "ブリジュラス",
    "ability": "じきゅうりょく",
    "nature": "ひかえめ",
    "ev": {
      "hp": 26,
      "atk": 0,
      "def": 1,
      "spatk": 31,
      "spdef": 0,
      "spd": 8
    },
    "item": "ピントレンズ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "りゅうせいぐん",
      "10まんボルト",
      "ラスターカノン",
      "きあいだめ"
    ],
    "role": "こうげき技を受けるたびぼうぎょが上がっていく特性を持ち、当てにくい技もピントレンズで命中させながら大技を連発する",
    "evidence_n": 101
  },
  {
    "id": 4,
    "species": "カバルドン",
    "ability": "すなおこし",
    "nature": "わんぱく",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 18,
      "spatk": 0,
      "spdef": 16,
      "spd": 0
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "じしん",
      "あくび",
      "なまける",
      "まもる"
    ],
    "role": "場に出ただけですなあらしを起こし、なまけるでHPを半分回復しながらあくびで眠りを誘う",
    "evidence_n": 87
  },
  {
    "id": 5,
    "species": "アシレーヌ",
    "ability": "げきりゅう",
    "nature": "ひかえめ",
    "ev": {
      "hp": 26,
      "atk": 0,
      "def": 0,
      "spatk": 28,
      "spdef": 0,
      "spd": 12
    },
    "item": "オボンのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ムーンフォース",
      "アクアジェット",
      "うたかたのアリア",
      "アンコール"
    ],
    "role": "HPが減るとみずの技がぐんと強くなる特性を持ち、アンコールで相手の技を封じながら戦う",
    "evidence_n": 79
  },
  {
    "id": 6,
    "species": "サザンドラ",
    "ability": "ふゆう",
    "nature": "ひかえめ",
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 8,
      "spatk": 26,
      "spdef": 0,
      "spd": 32
    },
    "item": "こだわりスカーフ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "りゅうせいぐん",
      "あくのはどう",
      "とんぼがえり",
      "かえんほうしゃ"
    ],
    "role": "じめん技を無効にする浮遊の特性を持ち、こだわりスカーフですばやさを上げてから幅広いタイプの技で押す",
    "evidence_n": 54
  },
  {
    "id": 7,
    "species": "メガメタグロス",
    "ability": "かたいツメ",
    "nature": "いじっぱり",
    "ev": {
      "hp": 10,
      "atk": 25,
      "def": 0,
      "spatk": 8,
      "spdef": 0,
      "spd": 23
    },
    "item": "メタグロスナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "バレットパンチ",
      "アームハンマー",
      "かみなりパンチ",
      "じしん"
    ],
    "role": "直接当てる技の威力が上がる特性を持ち、先制のバレットパンチから多彩なパンチ技を叩きこむ",
    "evidence_n": 53
  },
  {
    "id": 8,
    "species": "マスカーニャ",
    "ability": "へんげんじざい",
    "nature": "ようき",
    "ev": {
      "hp": 0,
      "atk": 32,
      "def": 2,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "こだわりスカーフ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "トリックフラワー",
      "とんぼがえり",
      "トリプルアクセル",
      "はたきおとす"
    ],
    "role": "技を出す直前にその技のタイプに変わる特性で弱点を突かれにくいまま、こだわりスカーフのすばやさで先制する",
    "evidence_n": 48
  },
  {
    "id": 9,
    "species": "メガマフォクシー",
    "ability": "ふゆう",
    "nature": "おくびょう",
    "ev": {
      "hp": 15,
      "atk": 0,
      "def": 6,
      "spatk": 28,
      "spdef": 0,
      "spd": 17
    },
    "item": "マフォクシナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "かえんほうしゃ",
      "わるだくみ",
      "サイコショック",
      "みがわり"
    ],
    "role": "じめん技を無効にする浮遊で安全に戦いながら、わるだくみでとくこうを上げてから攻めこむ",
    "evidence_n": 48
  },
  {
    "id": 10,
    "species": "メガギャラドス",
    "ability": "かたやぶり",
    "nature": "いじっぱり",
    "ev": {
      "hp": 3,
      "atk": 31,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "ギャラドスナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "りゅうのまい",
      "じしん",
      "たきのぼり",
      "パワーウィップ"
    ],
    "role": "相手の特性を無視できる特性を持ち、りゅうのまいで積んでからタイプの異なる技を使い分ける",
    "evidence_n": 43
  },
  {
    "id": 11,
    "species": "メガカイリュー",
    "ability": "マルチスケイル",
    "nature": "ひかえめ",
    "ev": {
      "hp": 9,
      "atk": 0,
      "def": 1,
      "spatk": 24,
      "spdef": 0,
      "spd": 32
    },
    "item": "カイリュナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "りゅうせいぐん",
      "エアスラッシュ",
      "かえんほうしゃ",
      "はねやすめ"
    ],
    "role": "HPが満タンの間はダメージを半分に抑える特性を持ち、はねやすめで回復しながら大技を連発する",
    "evidence_n": 40
  },
  {
    "id": 12,
    "species": "メガゲッコウガ",
    "ability": "へんげんじざい",
    "nature": "おくびょう",
    "ev": {
      "hp": 16,
      "atk": 0,
      "def": 0,
      "spatk": 28,
      "spdef": 1,
      "spd": 21
    },
    "item": "ゲッコウガナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ヘドロウェーブ",
      "れいとうビーム",
      "あくのはどう",
      "みずしゅりけん"
    ],
    "role": "技を出す直前にその技のタイプに変わる特性で、幅広いタイプの技を弱点を突かれずに使い分ける",
    "evidence_n": 34
  },
  {
    "id": 13,
    "species": "ドドゲザン",
    "ability": "そうだいしょう",
    "nature": "いじっぱり",
    "ev": {
      "hp": 12,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 22
    },
    "item": "くろいメガネ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ドゲザン",
      "ふいうち",
      "アイアンヘッド",
      "つるぎのまい"
    ],
    "role": "仲間がたおれるたびに技の威力が上がる特性を活かし、ふいうちの先制とつるぎのまいの積みを両立する",
    "evidence_n": 33
  },
  {
    "id": 14,
    "species": "キラフロル",
    "ability": "どくげしょう",
    "nature": "おくびょう",
    "ev": {
      "hp": 1,
      "atk": 0,
      "def": 1,
      "spatk": 32,
      "spdef": 0,
      "spd": 32
    },
    "item": "きあいのタスキ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ステルスロック",
      "パワージェム",
      "マッドショット",
      "だいちのちから"
    ],
    "role": "物理技を受けると相手の場にどくびしをまく特性を持ち、きあいのタスキで一度は耐えてステルスロックを置く",
    "evidence_n": 31
  },
  {
    "id": 15,
    "species": "アーマーガア",
    "ability": "プレッシャー",
    "nature": "わんぱく",
    "ev": {
      "hp": 32,
      "atk": 1,
      "def": 30,
      "spatk": 0,
      "spdef": 2,
      "spd": 1
    },
    "item": "オボンのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "はねやすめ",
      "ボディプレス",
      "とんぼがえり",
      "てっぺき"
    ],
    "role": "てっぺきでぼうぎょを上げ、その高いぼうぎょをそのままダメージにできるボディプレスをぶつける",
    "evidence_n": 27
  },
  {
    "id": 16,
    "species": "メガゲンガー",
    "ability": "かげふみ",
    "nature": "おくびょう",
    "ev": {
      "hp": 18,
      "atk": 0,
      "def": 0,
      "spatk": 13,
      "spdef": 3,
      "spd": 32
    },
    "item": "ゲンガナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "シャドーボール",
      "まもる",
      "みちづれ",
      "ヘドロウェーブ"
    ],
    "role": "相手を逃がさない特性を持ち、みちづれで相手を道連れにしたり幅広い技で攻める",
    "evidence_n": 26
  },
  {
    "id": 17,
    "species": "メガリザードンY",
    "ability": "ひでり",
    "nature": "ひかえめ",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 32,
      "spatk": 2,
      "spdef": 0,
      "spd": 0
    },
    "item": "リザードナイトY",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ソーラービーム",
      "かえんほうしゃ",
      "はねやすめ",
      "オーバーヒート"
    ],
    "role": "場に出ただけで天気を強い日ざしにする特性で、ソーラービームを一気に撃てるうえほのお技も強くなる",
    "evidence_n": 26
  },
  {
    "id": 18,
    "species": "メガクチート",
    "ability": "ちからもち",
    "nature": "いじっぱり",
    "ev": {
      "hp": 30,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 4
    },
    "item": "クチートナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ふいうち",
      "じゃれつく",
      "つるぎのまい",
      "かみなりパンチ"
    ],
    "role": "こうげきが2倍になる特性を持ち、先制のふいうちとつるぎのまいの積みで一気に押しきる",
    "evidence_n": 26
  },
  {
    "id": 19,
    "species": "メガメガニウム",
    "ability": "メガソーラー",
    "nature": "ひかえめ",
    "ev": {
      "hp": 20,
      "atk": 0,
      "def": 0,
      "spatk": 27,
      "spdef": 0,
      "spd": 19
    },
    "item": "メガニウムナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ソーラービーム",
      "ウェザーボール",
      "こうごうせい",
      "マジカルシャイン"
    ],
    "role": "技を出すたびに天気が強い日ざし扱いになる特性で、ソーラービームやウェザーボールを一気に強くしながらこうごうせいで回復する",
    "evidence_n": 24
  },
  {
    "id": 20,
    "species": "サーフゴー",
    "ability": "おうごんのからだ",
    "nature": "おくびょう",
    "ev": {
      "hp": 1,
      "atk": 0,
      "def": 0,
      "spatk": 32,
      "spdef": 1,
      "spd": 32
    },
    "item": "こだわりスカーフ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ゴールドラッシュ",
      "シャドーボール",
      "トリック",
      "10まんボルト"
    ],
    "role": "相手の変化技を受けつけない特性を持ち、こだわりスカーフのすばやさでゴールドラッシュを叩きこむ。トリックでスカーフを相手に押しつけることもできる",
    "evidence_n": 21
  },
  {
    "id": 21,
    "species": "メガミミロップ",
    "ability": "きもったま",
    "nature": "ようき",
    "ev": {
      "hp": 1,
      "atk": 32,
      "def": 1,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "ミミロップナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ねこだまし",
      "インファイト",
      "トリプルアクセル",
      "かみなりパンチ"
    ],
    "role": "ゴーストタイプにも通常・格闘技を当てられる特性で、ねこだましのひるみから一気に畳みかける",
    "evidence_n": 20
  },
  {
    "id": 22,
    "species": "メガハッサム",
    "ability": "テクニシャン",
    "nature": "いじっぱり",
    "ev": {
      "hp": 30,
      "atk": 23,
      "def": 0,
      "spatk": 0,
      "spdef": 13,
      "spd": 0
    },
    "item": "ハッサムナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "バレットパンチ",
      "インファイト",
      "つるぎのまい",
      "はねやすめ"
    ],
    "role": "威力の低い技を底上げする特性で、先制のバレットパンチをより強くしながらつるぎのまいで積む",
    "evidence_n": 20
  },
  {
    "id": 23,
    "species": "メガスターミー",
    "ability": "ちからもち",
    "nature": "いじっぱり",
    "ev": {
      "hp": 0,
      "atk": 32,
      "def": 1,
      "spatk": 0,
      "spdef": 1,
      "spd": 32
    },
    "item": "スターミナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "アクアブレイク",
      "アクアジェット",
      "クイックターン",
      "アイススピナー"
    ],
    "role": "こうげきが2倍になる特性を持ち、先制のアクアジェットや素早い交代のクイックターンで戦う",
    "evidence_n": 18
  },
  {
    "id": 24,
    "species": "メガバシャーモ",
    "ability": "かそく",
    "nature": "いじっぱり",
    "ev": {
      "hp": 2,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "バシャーモナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "フレアドライブ",
      "インファイト",
      "まもる",
      "つるぎのまい"
    ],
    "role": "毎ターンすばやさが上がっていく特性で、ターンを重ねるほど誰よりも速くなる",
    "evidence_n": 18
  },
  {
    "id": 25,
    "species": "メガルカリオ",
    "ability": "てきおうりょく",
    "nature": "ようき",
    "ev": {
      "hp": 2,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "ルカリオナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "インファイト",
      "コメットパンチ",
      "バレットパンチ",
      "つるぎのまい"
    ],
    "role": "タイプ一致の技の威力がさらに上がる特性で、つるぎのまいから多彩な技を叩きこむ",
    "evidence_n": 17
  },
  {
    "id": 26,
    "species": "ドラパルト",
    "ability": "すりぬけ",
    "nature": "おくびょう",
    "ev": {
      "hp": 2,
      "atk": 0,
      "def": 0,
      "spatk": 32,
      "spdef": 0,
      "spd": 32
    },
    "item": "いのちのたま",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "シャドーボール",
      "りゅうせいぐん",
      "10まんボルト",
      "のろい"
    ],
    "role": "みがわりや壁を無視してこうげきできる特性を持ち、とても速いすばやさで先に大技を撃つ",
    "evidence_n": 17
  },
  {
    "id": 27,
    "species": "メガムクホーク",
    "ability": "あまのじゃく",
    "nature": "ようき",
    "ev": {
      "hp": 31,
      "atk": 1,
      "def": 1,
      "spatk": 0,
      "spdef": 1,
      "spd": 32
    },
    "item": "ムクホークナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "インファイト",
      "ブレイブバード",
      "はねやすめ",
      "とんぼがえり"
    ],
    "role": "能力ランクの上げ下げが逆になる特性を持ち、はねやすめで回復しながらブレイブバードで撃ち抜く",
    "evidence_n": 17
  },
  {
    "id": 28,
    "species": "ブラッキー",
    "ability": "せいしんりょく",
    "nature": "ずぶとい",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 32,
      "spatk": 0,
      "spdef": 2,
      "spd": 0
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "イカサマ",
      "まもる",
      "ねがいごと",
      "あくび"
    ],
    "role": "ひるまなくなる特性でじっくり構え、ねがいごとで次のターンにHPを回復させながらあくびで眠りを誘う",
    "evidence_n": 15
  },
  {
    "id": 29,
    "species": "ヒートロトム",
    "ability": "ふゆう",
    "nature": "ひかえめ",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 0,
      "spatk": 5,
      "spdef": 29,
      "spd": 0
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "オーバーヒート",
      "ボルトチェンジ",
      "おにび",
      "ひかりのかべ"
    ],
    "role": "じめん技を無効にする浮遊の特性を持ち、おにびでやけどを広げつつひかりのかべで特殊技のダメージを抑える",
    "evidence_n": 15
  },
  {
    "id": 30,
    "species": "ウルガモス",
    "ability": "ほのおのからだ",
    "nature": "ずぶとい",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 32,
      "spatk": 0,
      "spdef": 0,
      "spd": 2
    },
    "item": "オボンのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ちょうのまい",
      "ほのおのまい",
      "あさのひざし",
      "おにび"
    ],
    "role": "直接当ててきた相手をやけどにすることがある特性を持ち、ちょうのまいとほのおのまいで能力を積み重ねる",
    "evidence_n": 15
  },
  {
    "id": 31,
    "species": "ソウブレイズ",
    "ability": "もらいび",
    "nature": "いじっぱり",
    "ev": {
      "hp": 1,
      "atk": 32,
      "def": 1,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "のろいのおふだ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ポルターガイスト",
      "むねんのつるぎ",
      "かげうち",
      "つるぎのまい"
    ],
    "role": "ほのお技を受けると自分のほのお技が強くなる特性を持ち、つるぎのまいで積んでからポルターガイストで攻める",
    "evidence_n": 14
  },
  {
    "id": 32,
    "species": "クエスパトラ",
    "ability": "かそく",
    "nature": "ひかえめ",
    "ev": {
      "hp": 1,
      "atk": 0,
      "def": 1,
      "spatk": 32,
      "spdef": 0,
      "spd": 32
    },
    "item": "きあいのタスキ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ルミナコリジョン",
      "マジカルシャイン",
      "シャドーボール",
      "まもる"
    ],
    "role": "毎ターンすばやさが上がっていく特性で、きあいのタスキで一度は耐えながらどんどん速くなっていく",
    "evidence_n": 14
  },
  {
    "id": 33,
    "species": "エルフーン",
    "ability": "いたずらごころ",
    "nature": "おくびょう",
    "ev": {
      "hp": 12,
      "atk": 0,
      "def": 16,
      "spatk": 0,
      "spdef": 6,
      "spd": 32
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ムーンフォース",
      "やどりぎのタネ",
      "アンコール",
      "みがわり"
    ],
    "role": "変化技を誰よりも先に出せる特性を持ち、みがわりやアンコールを素早く決めてから戦う",
    "evidence_n": 13
  },
  {
    "id": 34,
    "species": "メガライチュウY",
    "ability": "ノーガード",
    "nature": "おくびょう",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 1,
      "spatk": 9,
      "spdef": 1,
      "spd": 23
    },
    "item": "ライチュウナイトY",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "でんじほう",
      "きあいだま",
      "くさむすび",
      "アンコール"
    ],
    "role": "自分も相手も技が必ず当たる特性を持ち、当てにくいでんじほうやきあいだまを確実に命中させる",
    "evidence_n": 13
  },
  {
    "id": 35,
    "species": "ラウドボーン",
    "ability": "てんねん",
    "nature": "ずぶとい",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 32,
      "spatk": 2,
      "spdef": 0,
      "spd": 0
    },
    "item": "オボンのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "フレアソング",
      "なまける",
      "おにび",
      "シャドーボール"
    ],
    "role": "相手の能力上昇を無視してこうげきできる特性を持ち、なまけるで回復しながらフレアソングで歌い続ける",
    "evidence_n": 13
  },
  {
    "id": 36,
    "species": "カビゴン",
    "ability": "あついしぼう",
    "nature": "しんちょう",
    "ev": {
      "hp": 32,
      "atk": 2,
      "def": 0,
      "spatk": 0,
      "spdef": 32,
      "spd": 0
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "じしん",
      "じわれ",
      "ねむる",
      "うちおとす"
    ],
    "role": "ほのお・こおり技のダメージを半分に抑える特性でどっしり構え、ねむるで回復しながらじわれの一撃を狙う",
    "evidence_n": 13
  },
  {
    "id": 37,
    "species": "ウォッシュロトム",
    "ability": "ふゆう",
    "nature": "ずぶとい",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 14,
      "spatk": 0,
      "spdef": 20,
      "spd": 0
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ハイドロポンプ",
      "ボルトチェンジ",
      "おにび",
      "いたみわけ"
    ],
    "role": "じめん技を無効にする浮遊の特性を持ち、おにびでやけどを広げつついたみわけでHPを分け合う",
    "evidence_n": 12
  },
  {
    "id": 38,
    "species": "ドヒドイデ",
    "ability": "さいせいりょく",
    "nature": "わんぱく",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 32,
      "spatk": 0,
      "spdef": 2,
      "spd": 0
    },
    "item": "オボンのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "じこさいせい",
      "くろいきり",
      "どくどく",
      "まとわりつく"
    ],
    "role": "控えに戻るだけでHPが大きく回復する特性を持ち、どくどくでじわじわ相手を追い詰める",
    "evidence_n": 12
  },
  {
    "id": 39,
    "species": "メガピクシー",
    "ability": "マジックミラー",
    "nature": "ずぶとい",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 32,
      "spatk": 0,
      "spdef": 0,
      "spd": 2
    },
    "item": "ピクシナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ムーンフォース",
      "つきのひかり",
      "コスモパワー",
      "アシストパワー"
    ],
    "role": "相手の変化技をすべて跳ね返す特性を持ち、つきのひかりで回復しながらコスモパワーでぼうぎょ・とくぼうを積む",
    "evidence_n": 12
  },
  {
    "id": 40,
    "species": "ハラバリー",
    "ability": "でんきにかえる",
    "nature": "おだやか",
    "ev": {
      "hp": 31,
      "atk": 0,
      "def": 4,
      "spatk": 0,
      "spdef": 28,
      "spd": 3
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ボルトチェンジ",
      "みずびたし",
      "なまける",
      "どくどく"
    ],
    "role": "こうげきを受けると自分がじゅうでん状態になる特性を持ち、みずびたしで相手のほのお技を封じながら戦う",
    "evidence_n": 11
  },
  {
    "id": 41,
    "species": "ペリッパー",
    "ability": "あめふらし",
    "nature": "ひかえめ",
    "ev": {
      "hp": 2,
      "atk": 0,
      "def": 0,
      "spatk": 32,
      "spdef": 0,
      "spd": 32
    },
    "item": "きあいのタスキ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ぼうふう",
      "ウェザーボール",
      "とんぼがえり",
      "なみのり"
    ],
    "role": "場に出ただけで雨を降らせる特性を持ち、雨の中で命中率が上がるぼうふうとウェザーボールで攻める",
    "evidence_n": 11
  },
  {
    "id": 42,
    "species": "メガカメックス",
    "ability": "メガランチャー",
    "nature": "ひかえめ",
    "ev": {
      "hp": 19,
      "atk": 0,
      "def": 0,
      "spatk": 18,
      "spdef": 0,
      "spd": 29
    },
    "item": "カメックスナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "はどうだん",
      "あくのはどう",
      "れいとうビーム",
      "からをやぶる"
    ],
    "role": "波動系の技だけを1.5倍の威力で放つ特性を持つ特殊なアタッカー",
    "evidence_n": 11
  },
  {
    "id": 43,
    "species": "ニンフィア",
    "ability": "フェアリースキン",
    "nature": "ずぶとい",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 32,
      "spatk": 0,
      "spdef": 0,
      "spd": 2
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ハイパーボイス",
      "ねがいごと",
      "あくび",
      "まもる"
    ],
    "role": "ノーマル技までフェアリータイプに変えて強くする特性を持ち、ねがいごとで回復しながらじっくり粘る",
    "evidence_n": 10
  },
  {
    "id": 44,
    "species": "メガフシギバナ",
    "ability": "あついしぼう",
    "nature": "ずぶとい",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 27,
      "spatk": 0,
      "spdef": 7,
      "spd": 0
    },
    "item": "フシギバナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "だいちのちから",
      "やどりぎのタネ",
      "ギガドレイン",
      "こうごうせい"
    ],
    "role": "ほのお・こおり技のダメージを半分に抑える特性を持ち、やどりぎのタネやギガドレインでHPを吸いとって粘る",
    "evidence_n": 10
  },
  {
    "id": 45,
    "species": "メガリザードンX",
    "ability": "かたいツメ",
    "nature": "いじっぱり",
    "ev": {
      "hp": 2,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "リザードナイトX",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "フレアドライブ",
      "ニトロチャージ",
      "つるぎのまい",
      "げきりん"
    ],
    "role": "直接当てる技の威力が上がる特性を持ち、つるぎのまいで積みながらドラゴンと炎の両方でこうげきする",
    "evidence_n": 10
  },
  {
    "id": 46,
    "species": "メガヤドラン",
    "ability": "シェルアーマー",
    "nature": "ずぶとい",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 32,
      "spatk": 2,
      "spdef": 0,
      "spd": 0
    },
    "item": "ヤドランナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ねっとう",
      "なまける",
      "てっぺき",
      "ボディプレス"
    ],
    "role": "急所に当たらなくなる特性でどっしり構え、てっぺきで上げたぼうぎょをそのままボディプレスにする",
    "evidence_n": 10
  },
  {
    "id": 47,
    "species": "バイバニラ",
    "ability": "ゆきふらし",
    "nature": "ひかえめ",
    "ev": {
      "hp": 27,
      "atk": 0,
      "def": 0,
      "spatk": 30,
      "spdef": 0,
      "spd": 9
    },
    "item": "とけないこおり",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "フリーズドライ",
      "ふぶき",
      "こおりのつぶて",
      "ちょうはつ"
    ],
    "role": "場に出ただけで雪を降らせる特性を持ち、雪の中で命中率が上がるふぶきとみずタイプにも効くフリーズドライで攻める",
    "evidence_n": 8
  },
  {
    "id": 48,
    "species": "マンムー",
    "ability": "どんかん",
    "nature": "いじっぱり",
    "ev": {
      "hp": 0,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 2,
      "spd": 32
    },
    "item": "きあいのタスキ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "じしん",
      "こおりのつぶて",
      "がむしゃら",
      "つららばり"
    ],
    "role": "メロメロやちょうはつを受けつけない特性を持ち、きあいのタスキで一度は耐えてから地面と氷の技で押す",
    "evidence_n": 8
  },
  {
    "id": 49,
    "species": "エンペルト",
    "ability": "かちき",
    "nature": "ひかえめ",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 0,
      "spatk": 29,
      "spdef": 4,
      "spd": 1
    },
    "item": "シュカのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "なみのり",
      "れいとうビーム",
      "しんくうは",
      "くさむすび"
    ],
    "role": "相手に能力を下げられるとかえってとくこうが上がる特性を持ち、幅広いタイプの技で相手をとらえる",
    "evidence_n": 8
  },
  {
    "id": 50,
    "species": "マリルリ",
    "ability": "ちからもち",
    "nature": "いじっぱり",
    "ev": {
      "hp": 29,
      "atk": 32,
      "def": 2,
      "spatk": 0,
      "spdef": 2,
      "spd": 1
    },
    "item": "オボンのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "じゃれつく",
      "アクアジェット",
      "アクアブレイク",
      "はらだいこ"
    ],
    "role": "こうげきが2倍になる特性を持ち、はらだいこで一気に積んでから先制のアクアジェットで押しきる",
    "evidence_n": 8
  },
  {
    "id": 51,
    "species": "メガカエンジシ",
    "ability": "ほのおのたてがみ",
    "nature": "おくびょう",
    "ev": {
      "hp": 4,
      "atk": 0,
      "def": 0,
      "spatk": 32,
      "spdef": 0,
      "spd": 30
    },
    "item": "カエンジシナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "かえんほうしゃ",
      "オーバーヒート",
      "あくび",
      "ニトロチャージ"
    ],
    "role": "ほのお技の威力が1.5倍になる特性を持ち、あくびで眠りを誘いながら強力なほのお技で攻める",
    "evidence_n": 8
  },
  {
    "id": 52,
    "species": "オーロンゲ",
    "ability": "いたずらごころ",
    "nature": "わんぱく",
    "ev": {
      "hp": 31,
      "atk": 0,
      "def": 32,
      "spatk": 0,
      "spdef": 3,
      "spd": 0
    },
    "item": "たべのこし",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ソウルクラッシュ",
      "イカサマ",
      "すてゼリフ",
      "ねこだまし"
    ],
    "role": "変化技を誰よりも先に出せる特性を持ち、すてゼリフで能力を下げてから交代し、味方につなげる",
    "evidence_n": 7
  },
  {
    "id": 53,
    "species": "メガスコヴィラン",
    "ability": "とびだすハバネロ",
    "nature": "ひかえめ",
    "ev": {
      "hp": 31,
      "atk": 0,
      "def": 32,
      "spatk": 2,
      "spdef": 1,
      "spd": 0
    },
    "item": "スコヴィラナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "やどりぎのタネ",
      "ギガドレイン",
      "まもる",
      "しっとのほのお"
    ],
    "role": "こうげきを受けた相手をやけどにする特性を持ち、やどりぎのタネやギガドレインでHPを吸いとって粘る",
    "evidence_n": 7
  },
  {
    "id": 54,
    "species": "バンギラス",
    "ability": "すなおこし",
    "nature": "いじっぱり",
    "ev": {
      "hp": 32,
      "atk": 14,
      "def": 7,
      "spatk": 0,
      "spdef": 13,
      "spd": 0
    },
    "item": "ピントレンズ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "はたきおとす",
      "ほえる",
      "ストーンエッジ",
      "ステルスロック"
    ],
    "role": "場に出ただけですなあらしを起こす特性を持ち、ほえるで相手を無理やり交代させてからステルスロックを置く",
    "evidence_n": 7
  },
  {
    "id": 55,
    "species": "ミミズズ",
    "ability": "どしょく",
    "nature": "のんき",
    "ev": {
      "hp": 31,
      "atk": 0,
      "def": 3,
      "spatk": 0,
      "spdef": 32,
      "spd": 0
    },
    "item": "オボンのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "しっぽきり",
      "ステルスロック",
      "てっぺき",
      "ボディプレス"
    ],
    "role": "じめん技を吸収して逆に回復する特性を持ち、てっぺきで上げたぼうぎょをボディプレスにしてぶつける",
    "evidence_n": 6
  },
  {
    "id": 56,
    "species": "エルレイド",
    "ability": "きれあじ",
    "nature": "いじっぱり",
    "ev": {
      "hp": 26,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 8
    },
    "item": "いのちのたま",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "せいなるつるぎ",
      "サイコカッター",
      "つじぎり",
      "かげうち"
    ],
    "role": "切る技の威力が上がる特性を持ち、せいなるつるぎやつじぎりなど斬る技を中心に、いのちのたまで火力を底上げしてこうげきする",
    "evidence_n": 4
  },
  {
    "id": 57,
    "species": "ドリュウズ",
    "ability": "かたやぶり",
    "nature": "いじっぱり",
    "ev": {
      "hp": 0,
      "atk": 32,
      "def": 2,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "こだわりスカーフ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "じしん",
      "アイアンヘッド",
      "つのドリル",
      "いわなだれ"
    ],
    "role": "相手の特性を無視して技を出せる特性を持ち、こだわりスカーフのすばやさで一撃必殺のつのドリルなど幅広い技を繰り出す",
    "evidence_n": 4
  },
  {
    "id": 58,
    "species": "メガサーナイト",
    "ability": "フェアリースキン",
    "nature": "ひかえめ",
    "ev": {
      "hp": 32,
      "atk": 0,
      "def": 18,
      "spatk": 11,
      "spdef": 5,
      "spd": 0
    },
    "item": "サーナイトナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "ハイパーボイス",
      "サイコノイズ",
      "しんくうは",
      "マジカルフレイム"
    ],
    "role": "ノーマル技までフェアリータイプに変えて強くする特性を持ち、ハイパーボイスやサイコノイズで一気に押しきる",
    "evidence_n": 3
  },
  {
    "id": 59,
    "species": "ウインディ",
    "ability": "いかく",
    "nature": "ようき",
    "ev": {
      "hp": 2,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 32
    },
    "item": "オボンのみ",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "フレアドライブ",
      "しんそく",
      "インファイト",
      "おにび"
    ],
    "role": "出た瞬間に相手のこうげきを下げ、しんそくで先制もする",
    "evidence_n": null
  },
  {
    "id": 60,
    "species": "メガヘラクロス",
    "ability": "スキルリンク",
    "nature": "いじっぱり",
    "ev": {
      "hp": 32,
      "atk": 32,
      "def": 0,
      "spatk": 0,
      "spdef": 0,
      "spd": 2
    },
    "item": "ヘラクロスナイト",
    "item_pending": false,
    "substitute_item": null,
    "moves": [
      "つるぎのまい",
      "ミサイルばり",
      "ロックブラスト",
      "インファイト"
    ],
    "role": "連続技が必ず最大回数当たるようになり大ダメージを出す",
    "evidence_n": null
  }
];
