#!/usr/bin/env node
// reference/move_fx_map_draft_v1.json (技→エフェクト形状=shape 対応表) を window.MOVE_FX_MAP として
// 本番ページ(real_battle.html / online_battle.html)から<script src>で読める形に変換する。
// JSONを直接fetchするとCloudflare/パス問題があるため、JSアセットとして出す(先例=tools/_build_preset_builds_js.js → preset_builds.js)。
// 冪等: 何度実行してもJSONの内容から同じ move_fx_map.js を再生成するだけ。
//
// 出力にあたって1点だけ設計docから逸脱するパッチを当てる(2026-07-11 阿部さん確認5点の1つとして承認済み):
//   だいばくはつ/じばく = 設計doc本文では dust 流用(スコープを絞る案)だったが、阿部さんの確認で
//   「専用爆発形状でOK」と承認された(dust=土煙+地割れの地味な絵でなく、閃光+爆風の専用グリフ)。
//   reference/move_fx_map_draft_v1.json(設計の記録)自体は書き換えず、ここで生成時にのみ上書きする。
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');

const SRC = path.join(ROOT, 'reference/move_fx_map_draft_v1.json');
const OUT = path.join(ROOT, 'move_fx_map.js');

const data = JSON.parse(fs.readFileSync(SRC, 'utf8'));
if (!data || !data.defaults || !data.overrides || !data.shapes) {
  console.error('move_fx_map_draft_v1.json の形が想定と違う。中断。');
  process.exit(1);
}

// 専用爆発形状パッチ(dust→explosion。real_battle.html/online_battle.html側の描画にも
// 'explosion' 用のCSS/グリフを追加実装している。shapesカタログにも explosion を追記する)
const EXPLOSION_MOVES = ['だいばくはつ', 'じばく'];
for (const name of EXPLOSION_MOVES) {
  if (data.overrides[name] !== 'dust') {
    console.error(`想定外: overrides['${name}'] が 'dust' でない(=${data.overrides[name]})。draft側が変わっていないか確認。`);
    process.exit(1);
  }
  data.overrides[name] = 'explosion';
}
data.shapes.explosion = {
  desc: '専用爆発(だいばくはつ/じばく限定。dust流用でなく閃光+爆風の専用グリフ。2026-07-11 阿部さん承認)',
  impl: 'css(白閃光の中心+橙〜赤のradial-gradient爆風、dustより大きく明るい)',
  motion: 'burst',
};

const header =
`// Auto-generated by tools/_build_move_fx_map_js.js — 手で編集しない。
// 元データ: reference/move_fx_map_draft_v1.json (技→エフェクト形状=shape対応表・2026-07-11)
// 設計: 設計_技エフェクト対応表_2026-07-11.md
// real_battle.html / online_battle.html の shapeOf(mv) が読む(overrides→flagOrder→defaults の順)。
// 生成時パッチ: だいばくはつ/じばく = dust→explosion(専用爆発形状。2026-07-11 阿部さん確認で承認)
// 生成: ${new Date().toISOString()}
window.MOVE_FX_MAP = `;

const body = JSON.stringify(data, null, 2);
fs.writeFileSync(OUT, header + body + ';\n');
console.log(`move_fx_map.js を生成(shapes=${Object.keys(data.shapes).length} / overrides=${Object.keys(data.overrides).length}件) -> ${path.relative(ROOT, OUT)}`);
