#!/usr/bin/env node
// reference/battle_fx_cues.json (演出ツクール=fx_editor.htmlの書き出しSSOT) を window.BATTLE_FX_CUES として
// 本番ページ(real_battle.html / online_battle.html)から<script src>で読める形に変換する。
// 先例=tools/_build_move_fx_map_js.js → move_fx_map.js / tools/_build_preset_builds_js.js → preset_builds.js。
// 設計=設計_演出ツクール_2026-07-11.md 1-1/1-2、タスク=演出ツクールStep4(2026-07-11)。
//
// 冪等: 何度実行してもJSONの内容から同じ battle_fx_cues.js を再生成するだけ(手で編集しない)。
// SSOT(reference/battle_fx_cues.json)が無い/空でも壊れない(window.BATTLE_FX_CUES = {}; を出力する)。
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');

const SRC = path.join(ROOT, 'reference/battle_fx_cues.json');
const OUT = path.join(ROOT, 'battle_fx_cues.js');

let data = {};
if (fs.existsSync(SRC)) {
  const raw = fs.readFileSync(SRC, 'utf8').trim();
  if (raw) {
    try {
      data = JSON.parse(raw);
    } catch (e) {
      console.error(`reference/battle_fx_cues.json のJSONが壊れている: ${e.message}`);
      process.exit(1);
    }
  }
}
if (data == null || typeof data !== 'object' || Array.isArray(data)) {
  console.error('reference/battle_fx_cues.json の形が想定と違う(トップレベルはオブジェクト)。中断。');
  process.exit(1);
}

// キーごとに最低限の形チェック(move:/pattern:のシートだけ。__boardや将来のscene:等はそのまま素通し)。
let sheetCount = 0, doneCount = 0;
for (const [key, sheet] of Object.entries(data)) {
  if (key === '__board') continue;
  if (!/^(move|pattern|class|scene):/.test(key)) continue;
  sheetCount++;
  if (!sheet || !Array.isArray(sheet.cues)) {
    console.error(`想定外: ${key} に cues 配列が無い。中断。`);
    process.exit(1);
  }
  if (sheet.done === true) doneCount++;
}

const header =
`// Auto-generated by tools/_build_battle_fx_cues_js.js — 手で編集しない。
// 元データ: reference/battle_fx_cues.json (演出ツクール=fx_editor.htmlの書き出しSSOT)
// 設計: 設計_演出ツクール_2026-07-11.md(1-1キューシート/1-2 cuePlayer=上書きオーバーレイ方式)
// real_battle.html / online_battle.html の resolveCueSheet/playCueSheet(fx_primitives.js)が読む。
// キー = move:技名(個別上書き) / pattern:タイプ+分類(一括既定) / __board(エディタの立ち位置・本番では無視)。
// done===true のシートだけ本番で再生される(ドラフト中は従来の自動演出のまま=挙動不変)。
// 生成: ${new Date().toISOString()}
window.BATTLE_FX_CUES = `;

const body = JSON.stringify(data, null, 2);
fs.writeFileSync(OUT, header + body + ';\n');
console.log(`battle_fx_cues.js を生成(キー${Object.keys(data).length}件・シート${sheetCount}件・done${doneCount}件) -> ${path.relative(ROOT, OUT)}`);
