#!/usr/bin/env node
// reference/preset_builds_draft_v2.json (実戦58ビルド) を window.PRESET_BUILDS として
// 本番ページ(real_battle.html / online_battle.html)から<script src>で読める形に変換する。
// JSONを直接fetchするとCloudflare/パス問題があるため、JSアセットとして出す(2026-07-11 タスクB②)。
// 冪等: 何度実行してもJSONの内容から同じpreset_builds.jsを再生成するだけ。
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');

const SRC = path.join(ROOT, 'reference/preset_builds_draft_v2.json');
const OUT = path.join(ROOT, 'preset_builds.js');

const data = JSON.parse(fs.readFileSync(SRC, 'utf8'));
if (!Array.isArray(data) || !data.length) {
  console.error('preset_builds_draft_v2.json が空/配列でない。中断。');
  process.exit(1);
}

const header =
`// Auto-generated by tools/_build_preset_builds_js.js — 手で編集しない。
// 元データ: reference/preset_builds_draft_v2.json (実戦58構築プリセット・2026-07-11)
// real_battle.html / online_battle.html が相手(AI)チーム生成に使う。
// 生成: ${new Date().toISOString()}
window.PRESET_BUILDS = `;

const body = JSON.stringify(data, null, 2);
fs.writeFileSync(OUT, header + body + ';\n');
console.log(`preset_builds.js を生成(${data.length}件) -> ${path.relative(ROOT, OUT)}`);
